[CmdletBinding()]param()
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'Invoke-CergLo1R2AtomicHandoff.ps1')
. (Join-Path $PSScriptRoot 'New-CergLo1ResultGraph.ps1')
$ids=@('R2A-CE01-ConfirmationMismatch','R2A-CE02-SourceDrift','R2A-CE03-ExpiredBeforeOpen','R2A-CE04-ForeignProcess','R2A-CE05-A01WithoutFirstOpen','R2A-CE06-HeadDomainSplice','R2A-CE07-OrdinalOrdering','R2A-CE08-ImplementationBindings','R2A-CE09-RuntimeSelfConsistentSplice','R2A-CE10-FakeAssetRipperExecutable','R2A-SP01-AtomicHandoff')
$results=[Collections.Generic.List[object]]::new();function Add-AResult($id,[scriptblock]$body){try{&$body;$results.Add([pscustomobject][ordered]@{testId=$id;status='Passed';evidenceLocator="SyntheticFixture/$id/Assertions"})}catch{throw "$id failed: $($_.Exception.Message)"}}
function Test-AThrows([scriptblock]$body){$ok=$false;try{&$body|Out-Null}catch{$ok=$true};if(-not$ok){throw 'Expected failed-closed exception.'}}
function Copy-AObject($value){$value|ConvertTo-Json -Depth 100 -Compress|ConvertFrom-Json -Depth 100}
function Get-AOrdinalPlanRows([object[]]$members){$rows=[object[]]@($members|ForEach-Object{[pscustomobject][ordered]@{sourceMemberRefId=$_.memberId;sourceId=$_.sourceId;sourcePortableRelativePath=$_.portableRelativePath;stagingPortableRelativePath=('Extracted/CERG/SingleCharacter/LO-CERG1-R2/Input/'+$_.sourceId+'/'+$_.portableRelativePath);byteCount=[int64]$_.byteCount;sha256=$_.sha256}});[Array]::Sort($rows,[Collections.Generic.Comparer[object]]::Create([Comparison[object]]{param($a,$b)[string]::CompareOrdinal([string]$a.stagingPortableRelativePath,[string]$b.stagingPortableRelativePath)}));return $rows}
function Repair-AImplementationSets([object]$definition){$rows=[object[]]@($definition.implementationBindings);[Array]::Sort($rows,[Collections.Generic.Comparer[object]]::Create([Comparison[object]]{param($a,$b)[string]::CompareOrdinal([string]$a.implementationId,[string]$b.implementationId)}));$definition.implementationBindings=$rows;$definition.operation.implementationRefIds=[string[]]@($rows|ForEach-Object implementationId);return $definition}
function New-AImplementationBindings([string]$caseRoot){
    $repoRoot=[IO.Directory]::GetParent([IO.Directory]::GetParent($PSScriptRoot).FullName).FullName;$runtime=(Get-Process -Id $PID).Path
    $manifest=Get-Content -Raw -LiteralPath (Join-Path $repoRoot 'Tools\AssetImport\tool-manifest.json')|ConvertFrom-Json;$privateTool=[IO.Path]::GetFullPath([string]$manifest.assetRipper)
    $specs=@(
        [pscustomobject]@{artifactId='LO1-IA01';role='AssetRipperExecutable';version='1.3.14.0';pathKind='Private';portable=$null;implementation=$privateTool;runtime=$privateTool},
        [pscustomobject]@{artifactId='LO1-IF01';role='AssetRipperFolderInvoker';version='CERG-LO1-ASSETRIPPER-FOLDER-INVOKER/2';pathKind='Tracked';portable='Tools/AssetImport/Invoke-AssetRipperFolderExport.ps1';implementation=(Join-Path $repoRoot 'Tools\AssetImport\Invoke-AssetRipperFolderExport.ps1');runtime=$runtime},
        [pscustomobject]@{artifactId='T1V22-TG01';role='ExactLeafStagingWrapper';version='CERG-LO1-EXACT-STAGING/3';pathKind='Tracked';portable='Tools/AssetImport/Invoke-CergLo1ExactStaging.ps1';implementation=(Join-Path $repoRoot 'Tools\AssetImport\Invoke-CergLo1ExactStaging.ps1');runtime=$runtime},
        [pscustomobject]@{artifactId='T1V22-TG02';role='R01GraphProducer';version='CERG-LO1-R01-PRODUCER/5';pathKind='Tracked';portable='Tools/AssetImport/New-CergLo1ResultGraph.ps1';implementation=(Join-Path $repoRoot 'Tools\AssetImport\New-CergLo1ResultGraph.ps1');runtime=$runtime}
    )
    $rows=[object[]]@($specs|ForEach-Object{$ii=Get-Item -LiteralPath $_.implementation;$ri=Get-Item -LiteralPath $_.runtime;$is=Get-CergSha256Hex $ii.FullName;$rs=Get-CergSha256Hex $ri.FullName;$id='IMP-'+(Get-CergStructuredSha256 'cerg-lo1/implementation-id/1' @($_.role,$_.version,[int64]$ii.Length,$is,[int64]$ri.Length,$rs,@()));[pscustomobject][ordered]@{artifactId=$_.artifactId;implementationId=$id;implementationRole=$_.role;implementationVersion=$_.version;pathKind=$_.pathKind;portableTrackedPath=$_.portable;privateAbsoluteLeafPath=$(if($_.pathKind-ceq'Private'){$ii.FullName}else{$null});implementationByteCount=[int64]$ii.Length;implementationSha256=$is;runtimePrivateAbsoluteLeafPath=$ri.FullName;runtimeByteCount=[int64]$ri.Length;runtimeSha256=$rs;orderedArgumentTokens=@()}})
    [Array]::Sort($rows,[Collections.Generic.Comparer[object]]::Create([Comparison[object]]{param($a,$b)[string]::CompareOrdinal([string]$a.implementationId,[string]$b.implementationId)}));[pscustomobject]@{Rows=$rows;RefIds=[string[]]@($rows|ForEach-Object implementationId)}
}
$baseIds=@('R2-CE01-Missing','R2-CE02-Directory','R2-CE03-Reparse','R2-CE04-ByteDrift','R2-CE05-EqualSizeHashDrift','R2-CE06-SelectorConservation','R2-CE07-IndependentDisagreement','R2-CE08-StaleRun','R2-CE09-HiddenField','R2-CE10-ProducerSplice','R2-CE11-AncestorReparse','R2-SP01-ProductionConstructor','R2-SP02-IndependentValidator','R2-SP03-StagingConsumer','R2-AT01-SelectorMutation','R2-AT02-TupleMutation','R2-AT03-EvidenceMutation','R2-AT04-TimeMutation','R2-AT05-ImplementationMutation')
function Write-AJson($path,$value){[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($path))|Out-Null;[IO.File]::WriteAllText($path,(ConvertTo-CergCanonicalJsonValue $value),[Text.UTF8Encoding]::new($false))}
function New-AFixture($caseRoot){
    $sourceRoot=Join-Path $caseRoot 'Source';[IO.Directory]::CreateDirectory($sourceRoot)|Out-Null;$members=[Collections.Generic.List[object]]::new()
    $relativePaths=@('leaf/char_14401.unity3d','leaf/char_14401_animations.unity3d')+@(2..16|ForEach-Object{'leaf/{0:D2}.bin'-f$_})
    for($i=0;$i-lt17;$i++){$rel=$relativePaths[$i];$leaf=Join-Path $sourceRoot $rel.Replace('/','\');[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($leaf))|Out-Null;[IO.File]::WriteAllBytes($leaf,[Text.Encoding]::UTF8.GetBytes("a-plus-$i"));$members.Add([pscustomobject][ordered]@{memberId="OLD-$i";sourceId='synthetic';portableRelativePath=$rel;sizeBytes=[int64]([IO.FileInfo]::new($leaf).Length);sha256=(Get-FileHash -Algorithm SHA256 $leaf).Hash.ToLowerInvariant()})}
    $candidateHead=('1'*40);$freshnessHead=('2'*40);$executionHead=('3'*40);$candidate=[pscustomobject][ordered]@{schemaVersion='cerg-t1-candidate-lock/2.2.0';artifactId='CERG-T1V22-O01';contractHeadCommit=$candidateHead;status='Passed';selectedCandidateId='char_14401';attackAnchors=@();sourceMembers=@($members);discoveryObligations=@();evidenceItems=@();authorityScopes=@();subjects=@();relationships=@()};$candidatePath=Join-Path $caseRoot 'candidate.json';Write-AJson $candidatePath $candidate;$candidateSha=Get-CergSha256Hex $candidatePath
    $bindings=@([pscustomobject][ordered]@{sourceId='synthetic';privateAbsoluteReadOnlyRoot=$sourceRoot});$packet=Invoke-CergLo1R2FreshnessProducer $candidate $candidatePath $bindings $freshnessHead $candidateSha ([DateTimeOffset]::UtcNow.ToString('O'));$validator=Get-CergR2ValidatorImplementation;$refs=@($packet.producerImplementation.implementationId,$validator.implementationId);$rows=@($baseIds|ForEach-Object{[pscustomobject][ordered]@{testId=$_;status='Passed';evidenceRefIds=$refs}});$f01=Invoke-CergLo1R2FreshnessValidator $packet $bindings $rows[0..10] $rows[11..13] $rows[14..18];$f01Path=Join-Path $caseRoot 'freshness.json';[IO.File]::WriteAllText($f01Path,(ConvertTo-CergR2ValidatorJson $f01),[Text.UTF8Encoding]::new($false));$f01Sha=Get-CergSha256Hex $f01Path
    $attemptRoot=Join-Path $caseRoot 'Attempt';$planRows=@(Get-AOrdinalPlanRows $f01.currentMembers);$bytes=[int64](($planRows|Measure-Object byteCount -Sum).Sum);$memberIds=[string[]]@($planRows|ForEach-Object sourceMemberRefId);[Array]::Sort($memberIds,[StringComparer]::Ordinal)
    $implementations=New-AImplementationBindings $caseRoot
    $definition=[pscustomobject][ordered]@{schemaVersion='cerg-lo-cerg1-preflight-definition/1.2.0';artifactId='LO-CERG1-P02-DEFINITION';candidateLockSha256=$candidateSha;freshnessEvidenceSha256=$f01Sha;freshnessCheckRunId=$f01.checkRunId;freshnessValidatorFinishedAtUtc=$f01.validatorFinishedAtUtc;candidateContractHeadCommit=$candidateHead;freshnessContractHeadCommit=$freshnessHead;contractHeadCommit=$executionHead;selectedCandidateId='char_14401';createdAt=[DateTimeOffset]::UtcNow.ToString('O');sourceRootBindings=@([pscustomobject][ordered]@{sourceId='synthetic';privateAbsoluteReadOnlyRoot=$sourceRoot;rootFingerprint=('f'*64)});implementationBindings=@($implementations.Rows);operation=[pscustomobject][ordered]@{operationId='R2-OP';obligationRefIds=@('R2-OB');implementationRefIds=@($implementations.RefIds);inputMemberRefIds=$memberIds;expectedSubjectKinds=@();expectedRelationshipKinds=@();sourceReadMaxFiles=17;sourceReadMaxBytes=$bytes;maxDurationSeconds=60;maxResultRows=1;maxOutputFiles=100;maxOutputBytes=$bytes;stagingInputPortablePath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/Input';outputPortablePath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/Output';workPortablePath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/Work'};aggregateLimits=[pscustomobject][ordered]@{sourceReadMaxFiles=17;sourceReadMaxBytes=$bytes;maxDurationSeconds=60;maxResultRows=1;maxOutputFiles=100;maxOutputBytes=$bytes};stagingPlan=[pscustomobject][ordered]@{stagingInputPortablePath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/Input';stagingInventoryTemporaryPath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/staging-inventory.json.tmp';stagingInventoryPath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/staging-inventory.json';workPortablePath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/Work';outputPortablePath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/Output';memberRows=$planRows;memberCount=17;byteCount=$bytes;memberSetFingerprint=(Get-CergStructuredSha256 'cerg-lo1/staging-member-set/1' @($planRows))};status='Green';nextAction='RequestExactHumanConfirmationForR2P02'}
    $runner=Get-CergR2AtomicRunnerImplementation;$v14=@(1..23|ForEach-Object{'T1A3-TEST{0:D2}'-f$_})+@('T1A4-TEST24','T1A4-TEST25');$allTests=@($baseIds+$ids+$v14|ForEach-Object{[pscustomobject][ordered]@{testId=$_;status='Passed';evidenceLocator="SyntheticFixture/$_/Assertions"}})
    $repoRoot=[IO.Directory]::GetParent([IO.Directory]::GetParent($PSScriptRoot).FullName).FullName;$toolPaths=@('Tools/AssetImport/Invoke-CergLo1ExactStaging.ps1','Tools/AssetImport/Invoke-CergLo1R2AtomicHandoff.ps1','Tools/AssetImport/New-CergLo1Preflight.ps1','Tools/AssetImport/New-CergLo1R2Freshness.ps1','Tools/AssetImport/New-CergLo1ResultGraph.ps1','Tools/AssetImport/Test-CergLo1Pipeline.ps1','Tools/AssetImport/Test-CergLo1R2AtomicHandoff.ps1','Tools/AssetImport/Test-CergLo1R2Freshness.ps1','Tools/AssetImport/Test-CergLo1R2FreshnessPipeline.ps1','Tools/AssetImport/Invoke-AssetRipperFolderExport.ps1');$n=0;$toolRows=@($toolPaths|ForEach-Object{$leaf=[IO.Path]::Combine($repoRoot,$_.Replace('/',[IO.Path]::DirectorySeparatorChar));$item=Get-Item -LiteralPath $leaf;$n++;[pscustomobject][ordered]@{artifactId=('R2-A-T{0:D2}'-f$n);role='BoundImplementation';portableRelativePath=$_;byteCount=[int64]$item.Length;sha256=Get-CergSha256Hex $leaf}})
    $readiness=[pscustomobject][ordered]@{schemaVersion='cerg-r2-aplus-readiness/1.4.0';artifactId='R2-TO07';contractHeadCommit=$executionHead;toolRows=$toolRows;testRows=$allTests;status='Green';failures=@();nextAction='AwaitTotalControlAuditBeforeR2P02Generation'};$readinessPath=Join-Path $caseRoot 'readiness.json';Write-AJson $readinessPath $readiness
    $p02=New-CergLo1R2OrdinalPreflightObject -Definition $definition -Candidate $candidate -Freshness $f01 -Readiness $readiness -FreshnessEvidencePath $f01Path -AttemptPrivateAbsoluteRoot $attemptRoot;$p02Path=Join-Path $caseRoot 'preflight-ordinal.json';Write-AJson $p02Path $p02;$confirmation=Get-CergR2ConfirmationId $executionHead $f01Sha $f01.checkRunId $f01.currentMemberSetFingerprint (Get-CergSha256Hex $p02Path) $runner.implementationId
    [pscustomobject]@{Candidate=$candidate;CandidatePath=$candidatePath;F01Path=$f01Path;P01Path=$p02Path;ReadinessPath=$readinessPath;ConfirmationId=$confirmation;CandidateHead=$candidateHead;FreshnessHead=$freshnessHead;ExecutionHead=$executionHead;SourceRoot=$sourceRoot;AttemptRoot=$attemptRoot;Definition=$definition;F02Temp=(Join-Path $attemptRoot 'freshness-adjacency.json.tmp');F02=(Join-Path $attemptRoot 'freshness-adjacency.json');A01Temp=(Join-Path $attemptRoot 'attempt-state.json.tmp');A01=(Join-Path $attemptRoot 'attempt-state.json');H01Temp=(Join-Path $attemptRoot 'first-source-open.json.tmp');H01=(Join-Path $attemptRoot 'first-source-open.json');SITemp=(Join-Path $attemptRoot 'staging-inventory.json.tmp');SI=(Join-Path $attemptRoot 'staging-inventory.json');R01Temp=(Join-Path $attemptRoot 'result.json.tmp');R01=(Join-Path $attemptRoot 'result.json')}
}
function Invoke-AFixture($f,[string]$confirmation=$f.ConfirmationId){Invoke-CergLo1R2AtomicHandoff $f.CandidatePath $f.F01Path $f.P01Path $f.ReadinessPath $confirmation $f.F02Temp $f.F02 $f.A01Temp $f.A01 $f.H01Temp $f.H01 $f.SITemp $f.SI}
function Assert-AUpstream($f,$candidate,$preflight,$freshness,$adjacency,$readiness,$attempt,$staging){Assert-CergUpstreamBindings -Candidate $candidate -Preflight $preflight -Freshness $freshness -FreshnessEvidencePath $f.F01Path -AdjacencyFreshness $adjacency -AdjacencyFreshnessPath $f.F02 -Readiness $readiness -ReadinessPath $f.ReadinessPath -Attempt $attempt -Staging $staging -CandidatePath $f.CandidatePath -PreflightPath $f.P01Path -AttemptStatePath $f.A01 -FirstSourceOpenReceiptPath $f.H01 -StagingInventoryPath $f.SI -OutputRoot $preflight.stagingPlan.outputPrivateAbsolutePath}
$base=[IO.Path]::Combine([IO.Path]::GetTempPath(),'cerg-r2a-'+[guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($base)|Out-Null
try{
    Add-AResult $ids[0] {$f=New-AFixture (Join-Path $base 'confirm');Test-AThrows{Invoke-AFixture $f ('R2CONF-'+('0'*64))};$f01=Read-CergJsonFile $f.F01Path;$runner=Get-CergR2AtomicRunnerImplementation;$oldConfirmation='R2CONF-'+(Get-CergStructuredSha256 'cerg-r2/p01-confirmation-id/1' @($f.ExecutionHead,(Get-CergSha256Hex $f.F01Path),$f01.checkRunId,$f01.currentMemberSetFingerprint,(Get-CergSha256Hex $f.P01Path),$runner.implementationId));Test-AThrows{Invoke-AFixture $f $oldConfirmation};if([IO.File]::Exists($f.F02)-or[IO.File]::Exists($f.A01)){throw'Confirmation mismatch or old P01 confirmation created outputs.'}}
    Add-AResult $ids[1] {$f=New-AFixture (Join-Path $base 'drift');$leaf=Join-Path $f.SourceRoot ([string]$f.Candidate.sourceMembers[0].portableRelativePath).Replace('/','\');[IO.File]::WriteAllBytes($leaf,[Text.Encoding]::UTF8.GetBytes('drifted'));Test-AThrows{Invoke-AFixture $f};if([IO.File]::Exists($f.A01)){throw'Source drift created A01.'}}
    Add-AResult $ids[2] {$f=New-AFixture (Join-Path $base 'expired');[IO.Directory]::CreateDirectory($f.AttemptRoot)|Out-Null;[IO.File]::WriteAllText($f.A01,'{}');$token=New-CergR2AtomicHandoffToken 'i' 'r' ([DateTimeOffset]::UtcNow.AddSeconds(-11).ToString('O')) $f.A01 (Get-CergSha256Hex $f.A01) $f.H01Temp $f.H01;Test-AThrows{Complete-CergR2AtomicFirstSourceOpen $token 'R2M-expired'};$h=Read-CergJsonFile $f.H01;if($h.status-cne'FirstSourceOpenAfterDeadline'-or$h.LOUsedAfterFirstSourceOpen-ne2-or$h.nextAction-cne'FailClosedNoReuse'-or-not$token.firstSourceOpenObserved){throw'Late first open was not recorded as consumed failure.'}}
    Add-AResult $ids[3] {$f=New-AFixture (Join-Path $base 'foreign');[IO.Directory]::CreateDirectory($f.AttemptRoot)|Out-Null;[IO.File]::WriteAllText($f.A01,'{}');$token=New-CergR2AtomicHandoffToken 'i' 'r' ([DateTimeOffset]::UtcNow.ToString('O')) $f.A01 (Get-CergSha256Hex $f.A01) $f.H01Temp $f.H01;$token.processId=[int64]$PID+1;Test-AThrows{Assert-CergR2AtomicHandoffToken $token};$script:CergActiveR2HandoffSecret=$null}
    Add-AResult $ids[4] {$f=New-AFixture (Join-Path $base 'no-open');[IO.Directory]::CreateDirectory($f.AttemptRoot)|Out-Null;[IO.File]::WriteAllText($f.A01,'{}');$token=New-CergR2AtomicHandoffToken 'i' 'r' ([DateTimeOffset]::UtcNow.ToString('O')) $f.A01 (Get-CergSha256Hex $f.A01) $f.H01Temp $f.H01;if([IO.File]::Exists($f.H01)-or$token.firstSourceOpenObserved){throw'A01 alone consumed LO.'};$script:CergActiveR2HandoffSecret=$null}
    Add-AResult $ids[5] {$f=New-AFixture (Join-Path $base 'head-splice');$null=Invoke-AFixture $f;$p=Read-CergJsonFile $f.P01Path;$f01=Read-CergJsonFile $f.F01Path;$f02=Read-CergJsonFile $f.F02;$rd=Read-CergJsonFile $f.ReadinessPath;$a=Read-CergJsonFile $f.A01;$si=Read-CergJsonFile $f.SI;$null=Assert-AUpstream $f $f.Candidate $p $f01 $f02 $rd $a $si;$x=Copy-AObject $f.Candidate;$x.contractHeadCommit=('4'*40);Test-AThrows{Assert-AUpstream $f $x $p $f01 $f02 $rd $a $si};$x=Copy-AObject $f01;$x.contractHeadCommit=('4'*40);Test-AThrows{Assert-AUpstream $f $f.Candidate $p $x $f02 $rd $a $si};$x=Copy-AObject $p;$x.candidateContractHeadCommit=('4'*40);Test-AThrows{Assert-AUpstream $f $f.Candidate $x $f01 $f02 $rd $a $si};$x=Copy-AObject $p;$x.freshnessContractHeadCommit=('4'*40);Test-AThrows{Assert-AUpstream $f $f.Candidate $x $f01 $f02 $rd $a $si};$x=Copy-AObject $p;$x.contractHeadCommit=('4'*40);Test-AThrows{Assert-AUpstream $f $f.Candidate $x $f01 $f02 $rd $a $si};$x=Copy-AObject $f02;$x.contractHeadCommit=('4'*40);Test-AThrows{Assert-AUpstream $f $f.Candidate $p $f01 $x $rd $a $si};$x=Copy-AObject $rd;$x.contractHeadCommit=('4'*40);Test-AThrows{Assert-AUpstream $f $f.Candidate $p $f01 $f02 $x $a $si}}
    Add-AResult $ids[6] {$f=New-AFixture (Join-Path $base 'ordinal');$p=Read-CergJsonFile $f.P01Path;$f01=Read-CergJsonFile $f.F01Path;$originalCulture=[Globalization.CultureInfo]::CurrentCulture;try{$a=$null;$b=$null;[Globalization.CultureInfo]::CurrentCulture=[Globalization.CultureInfo]::GetCultureInfo('en-US');$a=@(Get-AOrdinalPlanRows $f01.currentMembers);[Globalization.CultureInfo]::CurrentCulture=[Globalization.CultureInfo]::GetCultureInfo('tr-TR');$b=@(Get-AOrdinalPlanRows $f01.currentMembers);if((ConvertTo-CergCanonicalJsonValue $a)-cne(ConvertTo-CergCanonicalJsonValue $b)-or(Get-CergStructuredSha256 'cerg-lo1/staging-member-set/1' @($a))-cne(Get-CergStructuredSha256 'cerg-lo1/staging-member-set/1' @($b))){throw'Ordinal positive sample varied by CurrentCulture.'}}finally{[Globalization.CultureInfo]::CurrentCulture=$originalCulture};$bad=Copy-AObject $p;$oldCulture=[Globalization.CultureInfo]::CurrentCulture;try{[Globalization.CultureInfo]::CurrentCulture=[Globalization.CultureInfo]::GetCultureInfo('en-US');$badRows=@($bad.stagingPlan.memberRows|Sort-Object stagingPortableRelativePath)}finally{[Globalization.CultureInfo]::CurrentCulture=$oldCulture};if((ConvertTo-CergCanonicalJsonValue $badRows)-ceq(ConvertTo-CergCanonicalJsonValue $p.stagingPlan.memberRows)){throw'Culture-sensitive negative vector did not differ from Ordinal.'};$bad.stagingPlan.memberRows=$badRows;$bad.stagingPlan.memberSetFingerprint=Get-CergStructuredSha256 'cerg-lo1/staging-member-set/1' @($badRows);Test-AThrows{Assert-CergLo1PreflightConsumerContract -Candidate $f.Candidate -Preflight $bad -Freshness $f01 -FreshnessEvidencePath $f.F01Path};$badDefinition=Copy-AObject $f.Definition;$badDefinition.stagingPlan.memberRows=$badRows;$badDefinition.stagingPlan.memberSetFingerprint=$bad.stagingPlan.memberSetFingerprint;Test-AThrows{New-CergLo1R2OrdinalPreflightObject -Definition $badDefinition -Candidate $f.Candidate -Freshness $f01 -Readiness (Read-CergJsonFile $f.ReadinessPath) -FreshnessEvidencePath $f.F01Path -AttemptPrivateAbsoluteRoot (Join-Path $f.AttemptRoot 'bad-definition')};$oldP01=Copy-AObject $p;$oldP01.schemaVersion='cerg-lo-cerg1-preflight/1.5.0';$oldP01.artifactId='LO-CERG1-P01';$oldP01.nextAction='RequestExactHumanConfirmationForLOCERG1';Test-AThrows{Assert-CergLo1PreflightConsumerContract -Candidate $f.Candidate -Preflight $oldP01 -Freshness $f01 -FreshnessEvidencePath $f.F01Path}}
    Add-AResult $ids[7] {$f=New-AFixture (Join-Path $base 'binding-red');$f01=Read-CergJsonFile $f.F01Path;$readiness=Read-CergJsonFile $f.ReadinessPath
        $x=Copy-AObject $f.Definition;$x.implementationBindings=@();$x.operation.implementationRefIds=@();Test-AThrows{New-CergLo1R2OrdinalPreflightObject -Definition $x -Candidate $f.Candidate -Freshness $f01 -Readiness $readiness -FreshnessEvidencePath $f.F01Path -AttemptPrivateAbsoluteRoot (Join-Path $f.AttemptRoot 'empty')}
        $x=Copy-AObject $f.Definition;$x.implementationBindings=@($x.implementationBindings|Select-Object -Skip 1);$x.operation.implementationRefIds=@($x.implementationBindings|ForEach-Object implementationId);Test-AThrows{New-CergLo1R2OrdinalPreflightObject -Definition $x -Candidate $f.Candidate -Freshness $f01 -Readiness $readiness -FreshnessEvidencePath $f.F01Path -AttemptPrivateAbsoluteRoot (Join-Path $f.AttemptRoot 'missing')}
        $x=Copy-AObject $f.Definition;$x.implementationBindings[1]=Copy-AObject $x.implementationBindings[0];Test-AThrows{New-CergLo1R2OrdinalPreflightObject -Definition $x -Candidate $f.Candidate -Freshness $f01 -Readiness $readiness -FreshnessEvidencePath $f.F01Path -AttemptPrivateAbsoluteRoot (Join-Path $f.AttemptRoot 'duplicate')}
        $x=Copy-AObject $f.Definition;$x.implementationBindings[0].implementationSha256=('0'*64);Test-AThrows{New-CergLo1R2OrdinalPreflightObject -Definition $x -Candidate $f.Candidate -Freshness $f01 -Readiness $readiness -FreshnessEvidencePath $f.F01Path -AttemptPrivateAbsoluteRoot (Join-Path $f.AttemptRoot 'hash')}
        $x=Copy-AObject $f.Definition;$x.operation.implementationRefIds=@($x.operation.implementationRefIds|Select-Object -Skip 1);Test-AThrows{New-CergLo1R2OrdinalPreflightObject -Definition $x -Candidate $f.Candidate -Freshness $f01 -Readiness $readiness -FreshnessEvidencePath $f.F01Path -AttemptPrivateAbsoluteRoot (Join-Path $f.AttemptRoot 'refs')}
        $r=Copy-AObject $readiness;$tracked=@($f.Definition.implementationBindings|Where-Object pathKind -CEQ 'Tracked')[0];$r.toolRows|Where-Object portableRelativePath -CEQ $tracked.portableTrackedPath|ForEach-Object{$_.sha256=('0'*64)};Test-AThrows{New-CergLo1R2OrdinalPreflightObject -Definition $f.Definition -Candidate $f.Candidate -Freshness $f01 -Readiness $r -FreshnessEvidencePath $f.F01Path -AttemptPrivateAbsoluteRoot (Join-Path $f.AttemptRoot 'readiness')}
        $p=Read-CergJsonFile $f.P01Path;$p.implementationBindings[0].implementationSha256=('0'*64);Write-AJson $f.P01Path $p;Test-AThrows{Invoke-AFixture $f};if([IO.File]::Exists($f.F02)-or[IO.File]::Exists($f.A01)){throw'Binding splice created handoff outputs.'}
    }
    Add-AResult $ids[8] {$f=New-AFixture (Join-Path $base 'runtime-splice');$f01=Read-CergJsonFile $f.F01Path;$readiness=Read-CergJsonFile $f.ReadinessPath;$x=Copy-AObject $f.Definition;$b=@($x.implementationBindings|Where-Object artifactId -CEQ 'LO1-IF01')[0];$splice=Join-Path ([IO.Directory]::GetParent([IO.Directory]::GetParent($PSScriptRoot).FullName).FullName) 'Tools\AssetImport\Invoke-AssetRipperFolderExport.ps1';$si=Get-Item $splice;$ss=Get-CergSha256Hex $splice;$b.runtimePrivateAbsoluteLeafPath=$si.FullName;$b.runtimeByteCount=[int64]$si.Length;$b.runtimeSha256=$ss;$b.implementationId='IMP-'+(Get-CergStructuredSha256 'cerg-lo1/implementation-id/1' @($b.implementationRole,$b.implementationVersion,[int64]$b.implementationByteCount,$b.implementationSha256,[int64]$b.runtimeByteCount,$b.runtimeSha256,@()));$x=Repair-AImplementationSets $x;Test-AThrows{New-CergLo1R2OrdinalPreflightObject -Definition $x -Candidate $f.Candidate -Freshness $f01 -Readiness $readiness -FreshnessEvidencePath $f.F01Path -AttemptPrivateAbsoluteRoot (Join-Path $f.AttemptRoot 'mutated')}}
    Add-AResult $ids[9] {$f=New-AFixture (Join-Path $base 'fake-exe');$f01=Read-CergJsonFile $f.F01Path;$readiness=Read-CergJsonFile $f.ReadinessPath;$x=Copy-AObject $f.Definition;$fake=Join-Path $f.AttemptRoot 'fake\AssetRipper.GUI.Free.exe';[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($fake))|Out-Null;[IO.File]::WriteAllBytes($fake,[Text.Encoding]::UTF8.GetBytes('not-an-assetripper-executable'));$b=@($x.implementationBindings|Where-Object artifactId -CEQ 'LO1-IA01')[0];$fi=Get-Item $fake;$fs=Get-CergSha256Hex $fake;$b.privateAbsoluteLeafPath=$fi.FullName;$b.runtimePrivateAbsoluteLeafPath=$fi.FullName;$b.implementationByteCount=[int64]$fi.Length;$b.runtimeByteCount=[int64]$fi.Length;$b.implementationSha256=$fs;$b.runtimeSha256=$fs;$b.implementationId='IMP-'+(Get-CergStructuredSha256 'cerg-lo1/implementation-id/1' @($b.implementationRole,$b.implementationVersion,[int64]$b.implementationByteCount,$b.implementationSha256,[int64]$b.runtimeByteCount,$b.runtimeSha256,@()));$x=Repair-AImplementationSets $x;Test-AThrows{New-CergLo1R2OrdinalPreflightObject -Definition $x -Candidate $f.Candidate -Freshness $f01 -Readiness $readiness -FreshnessEvidencePath $f.F01Path -AttemptPrivateAbsoluteRoot (Join-Path $f.AttemptRoot 'mutated')}}
    Add-AResult $ids[10] {$f=New-AFixture (Join-Path $base 'valid');$r=Invoke-AFixture $f;$h=Read-CergJsonFile $f.H01;if(-not[IO.File]::Exists($f.F02)-or-not[IO.File]::Exists($f.A01)-or-not[IO.File]::Exists($f.H01)-or-not[IO.File]::Exists($f.SI)-or$h.elapsedMilliseconds-gt10000-or$h.LOUsedBeforeFirstSourceOpen-ne1-or$h.LOUsedAfterFirstSourceOpen-ne2-or$r.stagingInventory.memberCount-ne17){throw'Atomic handoff success vector invalid.'};$a=Read-CergJsonFile $f.A01;$p=Read-CergJsonFile $f.P01Path;$f01=Read-CergJsonFile $f.F01Path;$f02=Read-CergJsonFile $f.F02;$rd=Read-CergJsonFile $f.ReadinessPath;$si=Read-CergJsonFile $f.SI;$null=Assert-AUpstream $f $f.Candidate $p $f01 $f02 $rd $a $si;if($p.candidateContractHeadCommit-cne$f.CandidateHead-or$p.freshnessContractHeadCommit-cne$f.FreshnessHead-or$p.contractHeadCommit-cne$f.ExecutionHead-or$f02.contractHeadCommit-cne$f.ExecutionHead-or$a.contractHeadCommit-cne$f.ExecutionHead){throw'Three-domain HEAD values were not preserved exactly.'};[IO.Directory]::CreateDirectory($p.stagingPlan.outputPrivateAbsolutePath)|Out-Null;[IO.File]::WriteAllText((Join-Path $p.stagingPlan.outputPrivateAbsolutePath 'synthetic.bin'),'result-graph-consumer',[Text.UTF8Encoding]::new($false));$r01=New-CergLo1ResultGraph -CandidateLockPath $f.CandidatePath -PreflightPath $f.P01Path -AttemptStatePath $f.A01 -StagingInventoryPath $f.SI -OutputRoot $p.stagingPlan.outputPrivateAbsolutePath -ResultTemporaryPath $f.R01Temp -ResultPath $f.R01 -FreshnessEvidencePath $f.F01Path -FirstSourceOpenReceiptPath $f.H01 -AdjacencyFreshnessPath $f.F02 -ReadinessPath $f.ReadinessPath;if(-not[IO.File]::Exists($f.R01)-or$r01.contractHeadCommit-cne$f.ExecutionHead){throw'ResultGraph did not consume the three-domain chain.'}}
    if($results.Count-ne11){throw'A+ test conservation failed.'};[pscustomobject][ordered]@{total=11;passed=11;failed=0;testRows=@($results)}|ConvertTo-Json -Depth 8
}finally{if([IO.Directory]::Exists($base)){Remove-Item -LiteralPath $base -Recurse -Force}}
