[CmdletBinding()]
param([string]$PublishReadinessPath,[string]$ContractHeadCommit)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'Invoke-MbacrControllerLocator.ps1')
. (Join-Path $PSScriptRoot 'Test-MbacrControllerLocation.ps1')

function Add-MbacrBE16 {param([Collections.Generic.List[byte]]$L,[uint16]$V);$L.Add([byte](($V-shr8)-band0xff));$L.Add([byte]($V-band0xff))}
function Add-MbacrBE32 {param([Collections.Generic.List[byte]]$L,[uint32]$V);3..0|ForEach-Object{$L.Add([byte](($V-shr(8*$_))-band0xff))}}
function Add-MbacrBE64 {param([Collections.Generic.List[byte]]$L,[uint64]$V);7..0|ForEach-Object{$L.Add([byte](($V-shr(8*$_))-band0xff))}}
function Add-MbacrLE16 {param([Collections.Generic.List[byte]]$L,[uint16]$V);0..1|ForEach-Object{$L.Add([byte](($V-shr(8*$_))-band0xff))}}
function Add-MbacrLE32 {param([Collections.Generic.List[byte]]$L,[uint32]$V);0..3|ForEach-Object{$L.Add([byte](($V-shr(8*$_))-band0xff))}}
function Add-MbacrLE64 {param([Collections.Generic.List[byte]]$L,[uint64]$V);0..7|ForEach-Object{$L.Add([byte](($V-shr(8*$_))-band0xff))}}
function Add-MbacrZ {param([Collections.Generic.List[byte]]$L,[string]$Text);$L.AddRange([Text.Encoding]::UTF8.GetBytes($Text));$L.Add(0)}

function New-MbacrSerializedFixture {
    param([int[]]$ObjectClassIds,[switch]$DuplicateObjectId,[byte[]]$PayloadBytes)
    if($null-eq$PayloadBytes){$PayloadBytes=[byte[]](1,2,3,4)}
    $types=[Collections.Generic.List[int]]::new();foreach($c in $ObjectClassIds){if(-not$types.Contains($c)){$types.Add($c)}}
    $meta=[Collections.Generic.List[byte]]::new();Add-MbacrZ $meta '2020.3.48f1';Add-MbacrLE32 $meta 5;$meta.Add(0);Add-MbacrLE32 $meta ([uint32]$types.Count)
    foreach($c in $types){Add-MbacrLE32 $meta ([uint32]$c);$meta.Add(0);Add-MbacrLE16 $meta 0;if($c-eq114){$meta.AddRange([byte[]]::new(16))};$meta.AddRange([byte[]]::new(16))}
    Add-MbacrLE32 $meta ([uint32]$ObjectClassIds.Count);while((48+$meta.Count)%4){$meta.Add(0)}
    $data=[Collections.Generic.List[byte]]::new();for($i=0;$i-lt$ObjectClassIds.Count;$i++){$objectPathId=$(if($DuplicateObjectId){1}else{$i+1});Add-MbacrLE64 $meta ([uint64]$objectPathId);Add-MbacrLE64 $meta ([uint64]$data.Count);Add-MbacrLE32 $meta ([uint32]$PayloadBytes.Length);Add-MbacrLE32 $meta ([uint32]$types.IndexOf($ObjectClassIds[$i]));$data.AddRange($PayloadBytes)}
    $header=[Collections.Generic.List[byte]]::new();$offset=48+$meta.Count;$size=$offset+$data.Count;Add-MbacrBE32 $header 0;Add-MbacrBE32 $header 0;Add-MbacrBE32 $header 22;Add-MbacrBE32 $header 0;$header.Add(0);$header.AddRange([byte[]](0,0,0));Add-MbacrBE32 $header ([uint32]$meta.Count);Add-MbacrBE64 $header ([uint64]$size);Add-MbacrBE64 $header ([uint64]$offset);Add-MbacrBE64 $header 0;$header.AddRange($meta.ToArray());$header.AddRange($data.ToArray());return ,([byte[]]$header.ToArray())
}

function Compress-MbacrLiteralLz4 {param([byte[]]$Bytes);$out=[Collections.Generic.List[byte]]::new();$length=$Bytes.Length;if($length -lt 15){$out.Add([byte]($length -shl 4))}else{$out.Add([byte]0xF0);$remain=$length-15;while($remain -ge 255){$out.Add([byte]255);$remain=$remain-255};$out.Add([byte]$remain)};$out.AddRange($Bytes);return ,([byte[]]$out.ToArray())}

function New-MbacrUnityFsFixture {
    param([byte[]]$SerializedBytes,[string]$NodeName='CAB-synthetic')
    [byte[]]$packedData=Compress-MbacrLiteralLz4 $SerializedBytes;$info=[Collections.Generic.List[byte]]::new();$info.AddRange([byte[]]::new(16));Add-MbacrBE32 $info 1;Add-MbacrBE32 $info ([uint32]$SerializedBytes.Length);Add-MbacrBE32 $info ([uint32]$packedData.Length);Add-MbacrBE16 $info 2;Add-MbacrBE32 $info 1;Add-MbacrBE64 $info 0;Add-MbacrBE64 $info ([uint64]$SerializedBytes.Length);Add-MbacrBE32 $info 0;Add-MbacrZ $info $NodeName;[byte[]]$plainInfo=$info.ToArray();[byte[]]$packedInfo=Compress-MbacrLiteralLz4 $plainInfo
    $prefix=[Collections.Generic.List[byte]]::new();Add-MbacrZ $prefix 'UnityFS';Add-MbacrBE32 $prefix 6;Add-MbacrZ $prefix '2020.3.48f1';Add-MbacrZ $prefix '2020.3.48f1';$total=$prefix.Count+8+4+4+4+$packedInfo.Length+$packedData.Length;Add-MbacrBE64 $prefix ([uint64]$total);Add-MbacrBE32 $prefix ([uint32]$packedInfo.Length);Add-MbacrBE32 $prefix ([uint32]$plainInfo.Length);Add-MbacrBE32 $prefix 0x42;$prefix.AddRange($packedInfo);$prefix.AddRange($packedData);return ,([byte[]]$prefix.ToArray())
}

function Write-MbacrFixtureBundle {param([string]$Path,[int[]]$Classes,[switch]$Duplicate,[byte[]]$Payload);[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($Path))|Out-Null;[IO.File]::WriteAllBytes($Path,(New-MbacrUnityFsFixture (New-MbacrSerializedFixture $Classes -DuplicateObjectId:$Duplicate -PayloadBytes $Payload)))}
function Copy-MbacrObject {param([object]$Value);return ((ConvertTo-MbacrProducerCanonicalJson $Value)|ConvertFrom-Json -Depth 100)}
function Test-MbacrThrows {param([scriptblock]$Action);try{&$Action;return $false}catch{return $true}}

function New-MbacrCase {
    param([string]$Root,[int[]]$AClasses=@(91),[int[]]$BClasses=@(1),[switch]$MissingA,[switch]$DuplicateA,[byte[]]$APayload,[string]$AName='a.unity3d',[string]$BName='b.unity3d',[string]$Subdirectory='bundles')
    [IO.Directory]::CreateDirectory($Root)|Out-Null;$aRel="$Subdirectory/$AName";$bRel="$Subdirectory/$BName";if(-not$MissingA){Write-MbacrFixtureBundle (Join-Path $Root $aRel) $AClasses -Duplicate:$DuplicateA -Payload $APayload};Write-MbacrFixtureBundle (Join-Path $Root $bRel) $BClasses
    $selectors=@([pscustomobject][ordered]@{selectorId='MBACR-S01';sourceId='pc-install';portableRelativePath=$aRel;ledgerByteCount=[int64]1;ledgerSha256=('1'*64)},[pscustomobject][ordered]@{selectorId='MBACR-S02';sourceId='pc-install';portableRelativePath=$bRel;ledgerByteCount=[int64]1;ledgerSha256=('2'*64)})
    $producerArgs=@('--root',$Root,'--selector','MBACR-S01','--selector','MBACR-S02');$validatorArgs=@('--root',$Root,'--validate','MBACR-S01','--validate','MBACR-S02')
    $rootBinding=Get-MbacrProducerRootBinding 'pc-install' $Root;$pb=Get-MbacrProducerBinding $rootBinding $producerArgs;$vb=Get-MbacrValidatorBinding $rootBinding $validatorArgs;$argsHash=Get-MbacrProducerStructuredHash 'mbacr/locator-arguments/1' @($producerArgs,$validatorArgs);$to01=('a'*64)
    $auth=[pscustomobject][ordered]@{authorizationId='';to01Sha256=$to01;sourceId='pc-install';rootFingerprint=$rootBinding.rootFingerprint;producerImplementationId=$pb.implementationId;validatorImplementationId=$vb.implementationId;orderedArgumentTokensFingerprint=$argsHash;selectorIds=@('MBACR-S01','MBACR-S02');maxProducerSourceOpens=2;maxValidatorSourceOpens=2;maxTotalSourceOpens=4;noLO=$true};$auth.authorizationId='MBACRLOC-'+(Get-MbacrProducerStructuredHash 'mbacr/locator-authorization/2' @($auth.to01Sha256,$auth.sourceId,$auth.rootFingerprint,$auth.producerImplementationId,$auth.validatorImplementationId,$auth.orderedArgumentTokensFingerprint,@($auth.selectorIds),2,2,4,$true))
    $attempt=[pscustomobject][ordered]@{schemaVersion='cerg-mbacr-locator-attempt/1.0.0';artifactId='MBACR-A00';contractHeadCommit=('b'*40);to01Sha256=$to01;locatorAuthorization=$auth;sourceRootBinding=$rootBinding;producerBinding=$pb;validatorBinding=$vb;selectorPlan=@($selectors|ForEach-Object{[pscustomobject][ordered]@{selectorId=$_.selectorId;sourceId=$_.sourceId;portableRelativePath=$_.portableRelativePath}});allowanceUsedBeforeInstall=0;allowanceUsedAfterInstall=1;status='ArmedNoSourceOpen';nextAction='RunExactFourLocatorOpens'}
    $limits=[pscustomobject][ordered]@{maxFilesRead=2;maxBytesRead=[int64]33554432;maxDurationSeconds=600;maxResultRows=32;maxChildProcesses=0}
    return [pscustomobject]@{Root=$Root;Selectors=$selectors;ProducerArgs=$producerArgs;ValidatorArgs=$validatorArgs;Attempt=$attempt;AttemptSha256=(Get-MbacrProducerCanonicalHash $attempt);Limits=$limits}
}

function Invoke-MbacrCase {param([object]$Case);$p=Invoke-MbacrControllerLocatorProducer -Attempt $Case.Attempt -AttemptSha256 $Case.AttemptSha256 -SelectorRows $Case.Selectors -SourceRoot $Case.Root -OrderedArgumentTokens $Case.ProducerArgs -Limits $Case.Limits;return Invoke-MbacrControllerLocatorValidator -Attempt $Case.Attempt -AttemptSha256 $Case.AttemptSha256 -ProducerPacket $p -SelectorRows $Case.Selectors -SourceRoot $Case.Root -OrderedArgumentTokens $Case.ValidatorArgs -Limits $Case.Limits}

$ids=@('MBACR-CE01-FilenameOnly','MBACR-CE02-RawStringOnly','MBACR-CE03-MissingLeaf','MBACR-CE04-AncestorReparse','MBACR-CE05-DuplicateObject','MBACR-CE06-ParserDisagreement','MBACR-CE07-LimitExceeded','MBACR-CE08-MultipleControllersOneSelector','MBACR-CE09-NonCanonicalFailureRejected','MBACR-CE10-LocatorReadWithoutAllowance','MBACR-CE11-WrongRoot','MBACR-CE12-ArgumentTamper','MBACR-CE13-AttemptReuseOrInterruption','MBACR-SP01-ParsedController')
$rows=[Collections.Generic.List[object]]::new();$base=Join-Path ([IO.Path]::GetTempPath()) ('mbacr-t1a-'+[Guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($base)|Out-Null
function Add-MbacrTest {param([string]$Id,[scriptblock]$Action);try{$ok=[bool](& $Action);if(-not$ok){throw 'Assertion returned false.'};$rows.Add([pscustomobject][ordered]@{testId=$Id;status='Passed';evidenceLocator="SyntheticFixture:$Id"})}catch{$rows.Add([pscustomobject][ordered]@{testId=$Id;status='Failed';evidenceLocator=("$($_.Exception.GetType().Name):$($_.Exception.Message)")})}}

try{
Add-MbacrTest $ids[0] { $c=New-MbacrCase (Join-Path $base 'ce01') -AClasses @(1) -AName 'AnimatorController.unity3d';$r=Invoke-MbacrCase $c;return $r.status-ceq'Failed'-and$r.partitions.locatedCount-eq0-and$r.partitions.notLocatedCount-eq2 }
Add-MbacrTest $ids[1] { $c=New-MbacrCase (Join-Path $base 'ce02') -AClasses @(1) -APayload ([Text.Encoding]::UTF8.GetBytes('AnimatorController'));$r=Invoke-MbacrCase $c;return $r.status-ceq'Failed'-and$r.locationRows.Count-eq0-and$r.selectorRows[0].status-ceq'NotLocated' }
Add-MbacrTest $ids[2] { $c=New-MbacrCase (Join-Path $base 'ce03') -MissingA;$r=Invoke-MbacrCase $c;return $r.status-ceq'Failed'-and$r.selectorRows[0].status-ceq'InvalidCurrentLeaf'-and@($r.failures|Where-Object detailCode -CEQ 'MissingLeaf').Count-eq1 }
Add-MbacrTest $ids[3] { $caseRoot=Join-Path $base 'ce04';$outside=Join-Path $base 'ce04-outside';$c=New-MbacrCase $outside;$root=Join-Path $caseRoot 'root';[IO.Directory]::CreateDirectory($root)|Out-Null;$link=Join-Path $root 'linked';New-Item -ItemType Junction -Path $link -Target (Join-Path $outside 'bundles')|Out-Null;$c2=New-MbacrCase $root -MissingA -AName 'missing' -BName 'placeholder' -Subdirectory 'other';$c2.Selectors[0].portableRelativePath='linked/a.unity3d';$c2.Selectors[1].portableRelativePath='linked/b.unity3d';$c2.Attempt.selectorPlan[0].portableRelativePath='linked/a.unity3d';$c2.Attempt.selectorPlan[1].portableRelativePath='linked/b.unity3d';$c2.AttemptSha256=Get-MbacrProducerCanonicalHash $c2.Attempt;$p=Invoke-MbacrControllerLocatorProducer -Attempt $c2.Attempt -AttemptSha256 $c2.AttemptSha256 -SelectorRows $c2.Selectors -SourceRoot $c2.Root -OrderedArgumentTokens $c2.ProducerArgs -Limits $c2.Limits;return @($p.selectorResults|Where-Object detailCode -CEQ 'AncestorReparse').Count-eq2 }
Add-MbacrTest $ids[4] { $c=New-MbacrCase (Join-Path $base 'ce05') -AClasses @(91,91) -DuplicateA;$r=Invoke-MbacrCase $c;return $r.status-ceq'Failed'-and$r.selectorRows[0].status-ceq'InvalidCurrentLeaf'-and@($r.failures|Where-Object detailCode -CEQ 'MalformedSerializedContainer').Count-eq1 }
Add-MbacrTest $ids[5] { $c=New-MbacrCase (Join-Path $base 'ce06');$p=Invoke-MbacrControllerLocatorProducer -Attempt $c.Attempt -AttemptSha256 $c.AttemptSha256 -SelectorRows $c.Selectors -SourceRoot $c.Root -OrderedArgumentTokens $c.ProducerArgs -Limits $c.Limits;$p.selectorResults[0].controllers=@();$r=Invoke-MbacrControllerLocatorValidator -Attempt $c.Attempt -AttemptSha256 $c.AttemptSha256 -ProducerPacket $p -SelectorRows $c.Selectors -SourceRoot $c.Root -OrderedArgumentTokens $c.ValidatorArgs -Limits $c.Limits;return $r.status-ceq'Failed'-and@($r.failures|Where-Object detailCode -CEQ 'ProducerValidatorMismatch').Count-eq1 }
Add-MbacrTest $ids[6] { $c=New-MbacrCase (Join-Path $base 'ce07');$c.Limits.maxBytesRead=1;$r=Invoke-MbacrCase $c;return $r.status-ceq'Failed'-and@($r.failures|Where-Object detailCode -CEQ 'BytesReadExceeded').Count-ge1 }
Add-MbacrTest $ids[7] { $c=New-MbacrCase (Join-Path $base 'ce08') -AClasses @(91,91);$r=Invoke-MbacrCase $c;return $r.status-ceq'ControllerLocated'-and$r.partitions.locatedCount-eq1-and$r.partitions.controllerLocationCount-eq2-and@($r.selectorRows|Where-Object status -CEQ 'Located').Count-eq1 }
Add-MbacrTest $ids[8] { $bad=New-MbacrValidatorFailure $null 'ConservationFailure' 'PartitionMismatch';$bad|Add-Member noteproperty detail 'free text';return (Test-MbacrThrows {Assert-MbacrValidatorFailureRows @($bad)|Out-Null}) }
Add-MbacrTest $ids[9] { $c=New-MbacrCase (Join-Path $base 'ce10');$c.Attempt.allowanceUsedAfterInstall=0;$mutatedSha=Get-MbacrProducerCanonicalHash $c.Attempt;return (Test-MbacrThrows {Invoke-MbacrControllerLocatorProducer -Attempt $c.Attempt -AttemptSha256 $mutatedSha -SelectorRows $c.Selectors -SourceRoot $c.Root -OrderedArgumentTokens $c.ProducerArgs -Limits $c.Limits|Out-Null}) }
Add-MbacrTest $ids[10] { $c=New-MbacrCase (Join-Path $base 'ce11');$other=Join-Path $base 'ce11-other';[IO.Directory]::CreateDirectory($other)|Out-Null;return (Test-MbacrThrows {Invoke-MbacrControllerLocatorProducer -Attempt $c.Attempt -AttemptSha256 $c.AttemptSha256 -SelectorRows $c.Selectors -SourceRoot $other -OrderedArgumentTokens $c.ProducerArgs -Limits $c.Limits|Out-Null}) }
Add-MbacrTest $ids[11] { $c=New-MbacrCase (Join-Path $base 'ce12');$tampered=@($c.ProducerArgs)+@('--extra');return (Test-MbacrThrows {Invoke-MbacrControllerLocatorProducer -Attempt $c.Attempt -AttemptSha256 $c.AttemptSha256 -SelectorRows $c.Selectors -SourceRoot $c.Root -OrderedArgumentTokens $tampered -Limits $c.Limits|Out-Null}) }
Add-MbacrTest $ids[12] { $c=New-MbacrCase (Join-Path $base 'ce13');$path=Join-Path $base 'ce13-attempt/locator-attempt.json';$first=Install-MbacrLocatorAttempt $c.Attempt $path;$secondRejected=Test-MbacrThrows {Install-MbacrLocatorAttempt $c.Attempt $path|Out-Null};return $secondRejected-and[IO.File]::Exists($path)-and(Get-MbacrProducerFileHash $path)-ceq$first.Sha256 }
Add-MbacrTest $ids[13] { $c=New-MbacrCase (Join-Path $base 'sp01');$r=Invoke-MbacrCase $c;return $r.status-ceq'ControllerLocated'-and$r.openCounts.producer-eq2-and$r.openCounts.validator-eq2-and$r.openCounts.total-eq4-and$r.locationRows.Count-eq1-and$r.locationRows[0].serializedTypeName-ceq'AnimatorController'-and$r.locationRows[0].serializedObjectId-ceq'1'-and$r.locationRows[0].proofKind-ceq'ParsedSerializedObject' }

if((@($rows|ForEach-Object testId)-join'|')-cne($ids-join'|')){throw 'Test row order mismatch.'}
$failed=@($rows|Where-Object status -cne 'Passed')
if($failed.Count){$failed|ForEach-Object{"$($_.testId): $($_.evidenceLocator)"}|Write-Host;throw "MBACR fixture failures: $($failed.Count)/$($ids.Count)"}
if($PublishReadinessPath){if($ContractHeadCommit-notmatch'^[0-9a-f]{40}$'){throw 'ContractHeadCommit must be exact lowercase 40-hex.'};$rootBinding=Get-MbacrProducerRootBinding 'pc-install' (Join-Path $base 'publish-root');$pb=Get-MbacrProducerBinding $rootBinding @();$vb=Get-MbacrValidatorBinding $rootBinding @();$toolRows=@([pscustomobject][ordered]@{artifactId=$pb.artifactId;role=$pb.role;portableTrackedPath=$pb.portableTrackedPath;implementationVersion=$pb.implementationVersion;byteCount=$pb.byteCount;sha256=$pb.sha256},[pscustomobject][ordered]@{artifactId=$vb.artifactId;role=$vb.role;portableTrackedPath=$vb.portableTrackedPath;implementationVersion=$vb.implementationVersion;byteCount=$vb.byteCount;sha256=$vb.sha256});$artifact=[pscustomobject][ordered]@{schemaVersion='cerg-mbacr-tooling-readiness/1.0.0';artifactId='MBACR-TO01';contractHeadCommit=$ContractHeadCommit;toolRows=$toolRows;testRows=@($rows);status='Green';failures=@();nextAction='AwaitTotalControlAuditBeforeMBACRT1B'};$final=[IO.Path]::GetFullPath($PublishReadinessPath);$tmp=$final+'.tmp';[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($final))|Out-Null;if([IO.File]::Exists($final)-or[IO.File]::Exists($tmp)){throw 'Readiness final/temp already exists.'};$bytes=[Text.UTF8Encoding]::new($false).GetBytes((ConvertTo-MbacrProducerCanonicalJson $artifact));$s=[IO.File]::Open($tmp,'CreateNew','Write','None');try{$s.Write($bytes,0,$bytes.Length);$s.Flush($true)}finally{$s.Dispose()};[IO.File]::Move($tmp,$final,$false);if((Get-MbacrProducerFileHash $final)-cne([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($bytes))).ToLowerInvariant()){throw 'Readiness reopen hash mismatch.'}}
[pscustomobject][ordered]@{status='Green';passed=$rows.Count;failed=0;testRows=@($rows);readinessPath=$(if($PublishReadinessPath){[IO.Path]::GetFullPath($PublishReadinessPath)}else{$null})}
}finally{$junction=Join-Path $base 'ce04/root/linked';if([IO.Directory]::Exists($junction)){[IO.Directory]::Delete($junction)};if([IO.Directory]::Exists($base)){[IO.Directory]::Delete($base,$true)}}
