[CmdletBinding()]
param([string]$PublishReadinessPath,[string]$ContractHeadCommit)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$script:MbacrActualProducerPath=Join-Path $PSScriptRoot 'Invoke-MbacrControllerLocator.ps1'
$script:MbacrActualValidatorPath=Join-Path $PSScriptRoot 'Test-MbacrControllerLocation.ps1'
. $script:MbacrActualProducerPath
. $script:MbacrActualValidatorPath

function Add-MbacrBE16 {param([Collections.Generic.List[byte]]$L,[uint16]$V);$L.Add([byte](($V-shr8)-band0xff));$L.Add([byte]($V-band0xff))}
function Add-MbacrBE32 {param([Collections.Generic.List[byte]]$L,[uint32]$V);3..0|ForEach-Object{$L.Add([byte](($V-shr(8*$_))-band0xff))}}
function Add-MbacrBE64 {param([Collections.Generic.List[byte]]$L,[uint64]$V);7..0|ForEach-Object{$L.Add([byte](($V-shr(8*$_))-band0xff))}}
function Add-MbacrLE16 {param([Collections.Generic.List[byte]]$L,[uint16]$V);0..1|ForEach-Object{$L.Add([byte](($V-shr(8*$_))-band0xff))}}
function Add-MbacrLE32 {param([Collections.Generic.List[byte]]$L,[uint32]$V);0..3|ForEach-Object{$L.Add([byte](($V-shr(8*$_))-band0xff))}}
function Add-MbacrLE64 {param([Collections.Generic.List[byte]]$L,[uint64]$V);0..7|ForEach-Object{$L.Add([byte](($V-shr(8*$_))-band0xff))}}
function Add-MbacrZ {param([Collections.Generic.List[byte]]$L,[string]$Text);$L.AddRange([Text.Encoding]::UTF8.GetBytes($Text));$L.Add(0)}

function New-MbacrSerializedFixture {
    param([int[]]$ObjectClassIds,[switch]$DuplicateObjectId,[byte[]]$PayloadBytes)
    if($null-eq$PayloadBytes){$PayloadBytes=[byte[]](1,2,3,4)}
    $types=[Collections.Generic.List[int]]::new();foreach($c in $ObjectClassIds){if(-not$types.Contains($c)){$types.Add($c)}}
    $meta=[Collections.Generic.List[byte]]::new();Add-MbacrZ $meta '2020.3.48f1';Add-MbacrLE32 $meta 5;$meta.Add(0);Add-MbacrLE32 $meta ([uint32]$types.Count)
    foreach($c in $types){Add-MbacrLE32 $meta ([uint32]$c);$meta.Add(0);Add-MbacrLE16 $meta 0;if($c-eq114){$meta.AddRange([byte[]]::new(16))};$meta.AddRange([byte[]]::new(16))}
    Add-MbacrLE32 $meta ([uint32]$ObjectClassIds.Count);while((48+$meta.Count)%4){$meta.Add(0)}
    $data=[Collections.Generic.List[byte]]::new();for($i=0;$i-lt$ObjectClassIds.Count;$i++){$objectPathId=$(if($DuplicateObjectId){1}else{$i+1});Add-MbacrLE64 $meta ([uint64]$objectPathId);Add-MbacrLE64 $meta ([uint64]$data.Count);Add-MbacrLE32 $meta ([uint32]$PayloadBytes.Length);Add-MbacrLE32 $meta ([uint32]$types.IndexOf($ObjectClassIds[$i]));$data.AddRange($PayloadBytes)}
    $header=[Collections.Generic.List[byte]]::new();$offset=48+$meta.Count;$size=$offset+$data.Count;Add-MbacrBE32 $header 0;Add-MbacrBE32 $header 0;Add-MbacrBE32 $header 22;Add-MbacrBE32 $header 0;$header.Add(0);$header.AddRange([byte[]](0,0,0));Add-MbacrBE32 $header ([uint32]$meta.Count);Add-MbacrBE64 $header ([uint64]$size);Add-MbacrBE64 $header ([uint64]$offset);Add-MbacrBE64 $header 0;$header.AddRange($meta.ToArray());$header.AddRange($data.ToArray());return ,([byte[]]$header.ToArray())
}

function Compress-MbacrLiteralLz4 {param([byte[]]$Bytes);$out=[Collections.Generic.List[byte]]::new();$length=$Bytes.Length;if($length -lt 15){$out.Add([byte]($length -shl 4))}else{$out.Add([byte]0xF0);$remain=$length-15;while($remain -ge 255){$out.Add([byte]255);$remain=$remain-255};$out.Add([byte]$remain)};$out.AddRange($Bytes);return ,([byte[]]$out.ToArray())}

function New-MbacrUnityFsFixture {
    param([byte[]]$SerializedBytes,[string]$NodeName='CAB-synthetic')
    [byte[]]$packedData=Compress-MbacrLiteralLz4 $SerializedBytes;$info=[Collections.Generic.List[byte]]::new();$info.AddRange([byte[]]::new(16));Add-MbacrBE32 $info 1;Add-MbacrBE32 $info ([uint32]$SerializedBytes.Length);Add-MbacrBE32 $info ([uint32]$packedData.Length);Add-MbacrBE16 $info 2;Add-MbacrBE32 $info 1;Add-MbacrBE64 $info 0;Add-MbacrBE64 $info ([uint64]$SerializedBytes.Length);Add-MbacrBE32 $info 0;Add-MbacrZ $info $NodeName;[byte[]]$plainInfo=$info.ToArray();[byte[]]$packedInfo=Compress-MbacrLiteralLz4 $plainInfo
    $prefix=[Collections.Generic.List[byte]]::new();Add-MbacrZ $prefix 'UnityFS';Add-MbacrBE32 $prefix 6;Add-MbacrZ $prefix '2020.3.48f1';Add-MbacrZ $prefix '2020.3.48f1';$total=$prefix.Count+8+4+4+4+$packedInfo.Length+$packedData.Length;Add-MbacrBE64 $prefix ([uint64]$total);Add-MbacrBE32 $prefix ([uint32]$packedInfo.Length);Add-MbacrBE32 $prefix ([uint32]$plainInfo.Length);Add-MbacrBE32 $prefix 0x42;$prefix.AddRange($packedInfo);$prefix.AddRange($packedData);return ,([byte[]]$prefix.ToArray())
}

function Write-MbacrFixtureBundle {param([string]$Path,[int[]]$Classes,[switch]$Duplicate,[byte[]]$Payload);[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($Path))|Out-Null;[IO.File]::WriteAllBytes($Path,(New-MbacrUnityFsFixture (New-MbacrSerializedFixture $Classes -DuplicateObjectId:$Duplicate -PayloadBytes $Payload)))}
function Copy-MbacrObject {param([object]$Value);return ((ConvertTo-MbacrProducerCanonicalJson $Value)|ConvertFrom-Json -Depth 100)}
function Test-MbacrThrows {param([scriptblock]$Action);try{&$Action;return $false}catch{return $true}}

function New-MbacrCase {
    param([string]$Root,[int[]]$AClasses=@(91),[int[]]$BClasses=@(1),[switch]$MissingA,[switch]$DuplicateA,[byte[]]$APayload,[string]$AName='a.unity3d',[string]$BName='b.unity3d',[string]$Subdirectory='bundles')
    [IO.Directory]::CreateDirectory($Root)|Out-Null;$aRel="$Subdirectory/$AName";$bRel="$Subdirectory/$BName";if(-not$MissingA){Write-MbacrFixtureBundle (Join-Path $Root $aRel) $AClasses -Duplicate:$DuplicateA -Payload $APayload};Write-MbacrFixtureBundle (Join-Path $Root $bRel) $BClasses
    $selectors=@([pscustomobject][ordered]@{selectorId='MBACR-S01';sourceId='pc-install';portableRelativePath=$aRel;ledgerByteCount=[int64]1;ledgerSha256=('1'*64)},[pscustomobject][ordered]@{selectorId='MBACR-S02';sourceId='pc-install';portableRelativePath=$bRel;ledgerByteCount=[int64]1;ledgerSha256=('2'*64)})
    $producerArgs=@('--root',$Root,'--selector','MBACR-S01','--selector','MBACR-S02');$validatorArgs=@('--root',$Root,'--validate','MBACR-S01','--validate','MBACR-S02')
    $rootBinding=Get-MbacrProducerRootBinding 'pc-install' $Root;$pb=Get-MbacrProducerBinding $rootBinding $producerArgs;$vb=Get-MbacrValidatorBinding $rootBinding $validatorArgs;$argsHash=Get-MbacrProducerStructuredHash 'mbacr/locator-arguments/1' @($producerArgs,$validatorArgs);$to02=('a'*64)
    $auth=[pscustomobject][ordered]@{authorizationId='';to02Sha256=$to02;sourceId='pc-install';rootFingerprint=$rootBinding.rootFingerprint;producerImplementationId=$pb.implementationId;validatorImplementationId=$vb.implementationId;orderedArgumentTokensFingerprint=$argsHash;selectorIds=@('MBACR-S01','MBACR-S02');maxProducerSourceOpens=2;maxValidatorSourceOpens=2;maxTotalSourceOpens=4;noLO=$true};$auth.authorizationId='MBACRLOC-'+(Get-MbacrProducerStructuredHash 'mbacr/locator-authorization/3' @($auth.to02Sha256,$auth.sourceId,$auth.rootFingerprint,$auth.producerImplementationId,$auth.validatorImplementationId,$auth.orderedArgumentTokensFingerprint,@($auth.selectorIds),2,2,4,$true))
    $attempt=[pscustomobject][ordered]@{schemaVersion='cerg-mbacr-locator-attempt/1.1.0';artifactId='MBACR-A00';contractHeadCommit=('b'*40);to02Sha256=$to02;locatorAuthorization=$auth;sourceRootBinding=$rootBinding;producerBinding=$pb;validatorBinding=$vb;selectorPlan=@($selectors|ForEach-Object{[pscustomobject][ordered]@{selectorId=$_.selectorId;sourceId=$_.sourceId;portableRelativePath=$_.portableRelativePath}});allowanceUsedBeforeInstall=0;allowanceUsedAfterInstall=1;status='ArmedNoSourceOpen';nextAction='RunExactFourLocatorOpens'}
    $limits=[pscustomobject][ordered]@{maxFilesRead=2;maxBytesRead=[int64]33554432;maxDurationSeconds=600;maxResultRows=32;maxChildProcesses=0}
    return [pscustomobject]@{Root=$Root;Selectors=$selectors;ProducerArgs=$producerArgs;ValidatorArgs=$validatorArgs;Attempt=$attempt;AttemptSha256=(Get-MbacrProducerCanonicalHash $attempt);Limits=$limits}
}

function Invoke-MbacrCase {param([object]$Case);$p=Invoke-MbacrControllerLocatorProducer -Attempt $Case.Attempt -AttemptSha256 $Case.AttemptSha256 -SelectorRows $Case.Selectors -SourceRoot $Case.Root -OrderedArgumentTokens $Case.ProducerArgs -Limits $Case.Limits;return Invoke-MbacrControllerLocatorValidator -Attempt $Case.Attempt -AttemptSha256 $Case.AttemptSha256 -ProducerPacket $p -SelectorRows $Case.Selectors -SourceRoot $Case.Root -OrderedArgumentTokens $Case.ValidatorArgs -Limits $Case.Limits}

$ids=@('MBACR-CE01-FilenameOnly','MBACR-CE02-RawStringOnly','MBACR-CE03-MissingLeaf','MBACR-CE04-AncestorReparse','MBACR-CE05-DuplicateObject','MBACR-CE06-ParserDisagreement','MBACR-CE07-LimitExceeded','MBACR-CE08-MultipleControllersOneSelector','MBACR-CE09-NonCanonicalFailureRejected','MBACR-CE10-LocatorReadWithoutAllowance','MBACR-CE11-WrongRoot','MBACR-CE12-ArgumentTamper','MBACR-CE13-AttemptReuseOrInterruption','MBACR-SP01-ParsedController')

function New-MbacrProductionCase {
    param([string]$Root,[int[]]$AClasses=@(91),[int[]]$BClasses=@(1),[switch]$MissingA)
    $repo=Join-Path $Root 'repo';$source=Join-Path $Root 'source';[IO.Directory]::CreateDirectory($repo)|Out-Null
    $case=New-MbacrCase $source -AClasses $AClasses -BClasses $BClasses -MissingA:$MissingA
    $aExact='Persistent_Store/AssetBundles/actor_common.unity3d';$bExact='xtlr_Data/StreamingAssets/InstallResource/actor_common.unity3d';$oldA=Join-Path $source $case.Selectors[0].portableRelativePath;$oldB=Join-Path $source $case.Selectors[1].portableRelativePath;$newA=Join-Path $source $aExact;$newB=Join-Path $source $bExact
    [IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($newA))|Out-Null;if([IO.File]::Exists($oldA)){[IO.File]::Move($oldA,$newA)};[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($newB))|Out-Null;[IO.File]::Move($oldB,$newB)
    $case.Selectors=@([pscustomobject][ordered]@{selectorId='MBACR-S01';sourceId='pc-install';portableRelativePath=$aExact;ledgerByteCount=[int64]10821270;ledgerSha256='8c485e107b27b5ff6862c79c61ba683eae7c46ed5fdd8afb203e8ff7de6dcf64'},[pscustomobject][ordered]@{selectorId='MBACR-S02';sourceId='pc-install';portableRelativePath=$bExact;ledgerByteCount=[int64]10777435;ledgerSha256='d66c4c505e3e577319dc776f76ac5a471487181b4fa9396e57bc2308639464fb'})
    $case.ProducerArgs=@('--root',$source,'--selector','MBACR-S01',$aExact,'--selector','MBACR-S02',$bExact);$case.ValidatorArgs=@('--root',$source,'--validate','MBACR-S01',$aExact,'--validate','MBACR-S02',$bExact)
    $toolDir=Join-Path $repo 'Tools/AssetImport';[IO.Directory]::CreateDirectory($toolDir)|Out-Null;$fixtureProducer=Join-Path $toolDir 'Invoke-MbacrControllerLocator.ps1';$fixtureValidator=Join-Path $toolDir 'Test-MbacrControllerLocation.ps1';[IO.File]::Copy($script:MbacrActualProducerPath,$fixtureProducer);[IO.File]::Copy($script:MbacrActualValidatorPath,$fixtureValidator);. $fixtureProducer;. $fixtureValidator
    $contractHead='c'*40;$rootBinding=Get-MbacrProducerRootBinding 'pc-install' $source;$pb=Get-MbacrProducerBinding $rootBinding $case.ProducerArgs;$vb=Get-MbacrValidatorBinding $rootBinding $case.ValidatorArgs
    $toolRows=@([pscustomobject][ordered]@{artifactId=$pb.artifactId;role=$pb.role;portableTrackedPath=$pb.portableTrackedPath;implementationVersion=$pb.implementationVersion;byteCount=[int64]$pb.byteCount;sha256=$pb.sha256},[pscustomobject][ordered]@{artifactId=$vb.artifactId;role=$vb.role;portableTrackedPath=$vb.portableTrackedPath;implementationVersion=$vb.implementationVersion;byteCount=[int64]$vb.byteCount;sha256=$vb.sha256})
    $testRows=@($ids|ForEach-Object{[pscustomobject][ordered]@{testId=$_;status='Passed';evidenceLocator="SyntheticFixture:$_"}})
    $readiness=[pscustomobject][ordered]@{schemaVersion='cerg-mbacr-tooling-readiness/1.1.0';artifactId='MBACR-TO02';contractHeadCommit=$contractHead;toolRows=$toolRows;testRows=$testRows;status='Green';failures=@();nextAction='AwaitTotalControlAuditBeforeMBACRT1B'}
    $readinessPath=Join-Path $repo 'Extracted/CERG/SingleCharacter/Recovery-BaseController/tooling-readiness-02.json';$published=Install-MbacrProducerCanonicalArtifact $readiness $readinessPath
    $i01Path=Join-Path $repo 'Extracted/CERG/SingleCharacter/LO-CERG1-R2/R01-P06/result.json';$i02Path=Join-Path $repo 'Extracted/Threads/019f4a24-5ca0-7002-9dc2-4a0e42ad3cbe/C1/source-corpus-ledger.json'
    [IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($i01Path))|Out-Null;[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($i02Path))|Out-Null;[IO.File]::WriteAllText($i01Path,'{"synthetic":"I01"}',$script:MbacrProducerUtf8);[IO.File]::WriteAllText($i02Path,'{"synthetic":"I02"}',$script:MbacrProducerUtf8)
    $inputRegistry=@([pscustomobject][ordered]@{artifactId='MBACR-I01';portableRelativePath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/R01-P06/result.json';byteCount=[int64]([IO.FileInfo]::new($i01Path).Length);sha256=Get-MbacrProducerFileHash $i01Path},[pscustomobject][ordered]@{artifactId='MBACR-I02';portableRelativePath='Extracted/Threads/019f4a24-5ca0-7002-9dc2-4a0e42ad3cbe/C1/source-corpus-ledger.json';byteCount=[int64]([IO.FileInfo]::new($i02Path).Length);sha256=Get-MbacrProducerFileHash $i02Path})
    $argumentsFingerprint=Get-MbacrProducerStructuredHash 'mbacr/locator-arguments/1' @($case.ProducerArgs,$case.ValidatorArgs)
    $authId='MBACRLOC-'+(Get-MbacrProducerStructuredHash 'mbacr/locator-authorization/3' @($published.Sha256,'pc-install',$rootBinding.rootFingerprint,$pb.implementationId,$vb.implementationId,$argumentsFingerprint,@('MBACR-S01','MBACR-S02'),2,2,4,$true))
    return [pscustomobject]@{RepositoryRoot=$repo;SourceRoot=$source;Selectors=$case.Selectors;ProducerArgs=$case.ProducerArgs;ValidatorArgs=$case.ValidatorArgs;Limits=$case.Limits;InputArtifactRegistry=$inputRegistry;AuthorizationId=$authId;To02Sha256=$published.Sha256;RootFingerprint=$rootBinding.rootFingerprint;ProducerImplementationId=$pb.implementationId;ValidatorImplementationId=$vb.implementationId;ArgumentsFingerprint=$argumentsFingerprint;Readiness=$readiness;ProducerBinding=$pb;ValidatorBinding=$vb}
}

function Invoke-MbacrProductionCase {
    param([object]$Case)
    return Invoke-MbacrControllerLocatorForegroundCore -RepositoryRoot $Case.RepositoryRoot -SourceRoot $Case.SourceRoot -SelectorRows $Case.Selectors -ProducerOrderedArgumentTokens $Case.ProducerArgs -ValidatorOrderedArgumentTokens $Case.ValidatorArgs -Limits $Case.Limits -InputArtifactRegistry $Case.InputArtifactRegistry -ExactAuthorizationId $Case.AuthorizationId -ExactTo02Sha256 $Case.To02Sha256 -ExactRootFingerprint $Case.RootFingerprint -ExactProducerImplementationId $Case.ProducerImplementationId -ExactValidatorImplementationId $Case.ValidatorImplementationId -ExactArgumentsFingerprint $Case.ArgumentsFingerprint
}

$rows=[Collections.Generic.List[object]]::new();$base=Join-Path ([IO.Path]::GetTempPath()) ('mbacr-t1a-'+[Guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($base)|Out-Null
function Add-MbacrTest {param([string]$Id,[scriptblock]$Action);try{$ok=[bool](& $Action);if(-not$ok){throw 'Assertion returned false.'};$rows.Add([pscustomobject][ordered]@{testId=$Id;status='Passed';evidenceLocator="SyntheticFixture:$Id"})}catch{$rows.Add([pscustomobject][ordered]@{testId=$Id;status='Failed';evidenceLocator=("$($_.Exception.GetType().Name):$($_.Exception.Message)")})}}

try{
Add-MbacrTest $ids[0] { $c=New-MbacrCase (Join-Path $base 'ce01') -AClasses @(1) -AName 'AnimatorController.unity3d';$r=Invoke-MbacrCase $c;return $r.status-ceq'Failed'-and$r.partitions.locatedCount-eq0-and$r.partitions.notLocatedCount-eq2 }
Add-MbacrTest $ids[1] { $c=New-MbacrCase (Join-Path $base 'ce02') -AClasses @(1) -APayload ([Text.Encoding]::UTF8.GetBytes('AnimatorController'));$r=Invoke-MbacrCase $c;return $r.status-ceq'Failed'-and$r.locationRows.Count-eq0-and$r.selectorRows[0].status-ceq'NotLocated' }
Add-MbacrTest $ids[2] { $c=New-MbacrProductionCase (Join-Path $base 'ce03') -MissingA;$published=Invoke-MbacrProductionCase $c;$r=$published.artifact;$missing=@($r.failures|Where-Object detailCode -CEQ 'MissingLeaf');$ok=$r.schemaVersion-ceq'cerg-mbacr-controller-location/1.1.0'-and$r.artifactId-ceq'MBACR-L01'-and$r.status-ceq'Failed'-and$r.selectorRows[0].status-ceq'InvalidCurrentLeaf'-and$null-eq$r.selectorRows[0].currentByteCount-and$null-eq$r.selectorRows[0].currentSha256-and$missing.Count-eq1-and$missing[0].reasonCode-ceq'InputIdentityFailure'-and$r.openCounts.producer-eq1-and$r.openCounts.validator-eq1-and$r.openCounts.total-eq2-and@($r.openRows).Count-eq2-and[IO.File]::Exists($published.attemptPath)-and[IO.File]::Exists($published.path);if(-not$ok){throw ($r|ConvertTo-Json -Depth 8 -Compress)};return $true }
Add-MbacrTest $ids[3] { $caseRoot=Join-Path $base 'ce04';$outside=Join-Path $base 'ce04-outside';$c=New-MbacrCase $outside;$root=Join-Path $caseRoot 'root';[IO.Directory]::CreateDirectory($root)|Out-Null;$link=Join-Path $root 'linked';New-Item -ItemType Junction -Path $link -Target (Join-Path $outside 'bundles')|Out-Null;$c2=New-MbacrCase $root -MissingA -AName 'missing' -BName 'placeholder' -Subdirectory 'other';$c2.Selectors[0].portableRelativePath='linked/a.unity3d';$c2.Selectors[1].portableRelativePath='linked/b.unity3d';$c2.Attempt.selectorPlan[0].portableRelativePath='linked/a.unity3d';$c2.Attempt.selectorPlan[1].portableRelativePath='linked/b.unity3d';$c2.AttemptSha256=Get-MbacrProducerCanonicalHash $c2.Attempt;$p=Invoke-MbacrControllerLocatorProducer -Attempt $c2.Attempt -AttemptSha256 $c2.AttemptSha256 -SelectorRows $c2.Selectors -SourceRoot $c2.Root -OrderedArgumentTokens $c2.ProducerArgs -Limits $c2.Limits;return @($p.selectorResults|Where-Object detailCode -CEQ 'AncestorReparse').Count-eq2 }
Add-MbacrTest $ids[4] { $c=New-MbacrCase (Join-Path $base 'ce05') -AClasses @(91,91) -DuplicateA;$r=Invoke-MbacrCase $c;return $r.status-ceq'Failed'-and$r.selectorRows[0].status-ceq'InvalidCurrentLeaf'-and@($r.failures|Where-Object detailCode -CEQ 'MalformedSerializedContainer').Count-eq1 }
Add-MbacrTest $ids[5] { $c=New-MbacrCase (Join-Path $base 'ce06');$p=Invoke-MbacrControllerLocatorProducer -Attempt $c.Attempt -AttemptSha256 $c.AttemptSha256 -SelectorRows $c.Selectors -SourceRoot $c.Root -OrderedArgumentTokens $c.ProducerArgs -Limits $c.Limits;$p.selectorResults[0].controllers=@();$r=Invoke-MbacrControllerLocatorValidator -Attempt $c.Attempt -AttemptSha256 $c.AttemptSha256 -ProducerPacket $p -SelectorRows $c.Selectors -SourceRoot $c.Root -OrderedArgumentTokens $c.ValidatorArgs -Limits $c.Limits;return $r.status-ceq'Failed'-and@($r.failures|Where-Object detailCode -CEQ 'ProducerValidatorMismatch').Count-eq1 }
Add-MbacrTest $ids[6] { $c=New-MbacrProductionCase (Join-Path $base 'ce07') -AClasses @(1..33|ForEach-Object{91});$r=(Invoke-MbacrProductionCase $c).artifact;$limit=@($r.failures|Where-Object detailCode -CEQ 'ResultRowsExceeded');$opened=@($r.openRows|Where-Object selectorId -CEQ 'MBACR-S01');$ok=$r.status-ceq'Failed'-and$r.limits.maxResultRows-eq32-and$limit.Count-eq1-and$limit[0].reasonCode-ceq'LimitExceeded'-and$null-ne$r.selectorRows[0].currentByteCount-and$r.selectorRows[0].currentSha256-match'^[0-9a-f]{64}$'-and$opened.Count-eq2-and@($opened|Where-Object sha256 -cne $r.selectorRows[0].currentSha256).Count-eq0-and$r.openCounts.producer-eq2-and$r.openCounts.validator-eq2-and$r.openCounts.total-eq4;if(-not$ok){throw ($r|ConvertTo-Json -Depth 8 -Compress)};return $true }
Add-MbacrTest $ids[7] { $c=New-MbacrCase (Join-Path $base 'ce08') -AClasses @(91,91);$r=Invoke-MbacrCase $c;return $r.status-ceq'ControllerLocated'-and$r.partitions.locatedCount-eq1-and$r.partitions.controllerLocationCount-eq2-and@($r.selectorRows|Where-Object status -CEQ 'Located').Count-eq1 }
Add-MbacrTest $ids[8] { $bad=New-MbacrValidatorFailure $null 'ConservationFailure' 'PartitionMismatch';$bad|Add-Member noteproperty detail 'free text';$failureRejected=Test-MbacrThrows {Assert-MbacrValidatorFailureRows @($bad)|Out-Null};$c=New-MbacrProductionCase (Join-Path $base 'ce09');$extra=Copy-MbacrObject $c.Readiness;$extra|Add-Member noteproperty extraField $true;$extraRejected=Test-MbacrThrows {Assert-MbacrProducerReadiness $extra (Get-MbacrProducerCanonicalHash $extra) $c.ProducerBinding $c.ValidatorBinding};$reordered=[pscustomobject][ordered]@{artifactId='MBACR-TO02';schemaVersion='cerg-mbacr-tooling-readiness/1.1.0';contractHeadCommit=('c'*40);toolRows=$c.Readiness.toolRows;testRows=$c.Readiness.testRows;status='Green';failures=@();nextAction='AwaitTotalControlAuditBeforeMBACRT1B'};$orderRejected=Test-MbacrThrows {Assert-MbacrProducerReadiness $reordered (Get-MbacrProducerCanonicalHash $reordered) $c.ProducerBinding $c.ValidatorBinding};return $failureRejected-and$extraRejected-and$orderRejected }
Add-MbacrTest $ids[9] { $c=New-MbacrCase (Join-Path $base 'ce10');$c.Attempt.allowanceUsedAfterInstall=0;$mutatedSha=Get-MbacrProducerCanonicalHash $c.Attempt;$allowanceRejected=Test-MbacrThrows {Invoke-MbacrControllerLocatorProducer -Attempt $c.Attempt -AttemptSha256 $mutatedSha -SelectorRows $c.Selectors -SourceRoot $c.Root -OrderedArgumentTokens $c.ProducerArgs -Limits $c.Limits|Out-Null};$p=New-MbacrProductionCase (Join-Path $base 'ce10-fixed-input');$publicRejected=Test-MbacrThrows {Invoke-MbacrControllerLocatorForegroundRun -RepositoryRoot $p.RepositoryRoot -SourceRoot $p.SourceRoot -SelectorRows $p.Selectors -ProducerOrderedArgumentTokens $p.ProducerArgs -ValidatorOrderedArgumentTokens $p.ValidatorArgs -Limits $p.Limits -ExactAuthorizationId $p.AuthorizationId -ExactTo02Sha256 $p.To02Sha256 -ExactRootFingerprint $p.RootFingerprint -ExactProducerImplementationId $p.ProducerImplementationId -ExactValidatorImplementationId $p.ValidatorImplementationId -ExactArgumentsFingerprint $p.ArgumentsFingerprint|Out-Null};$a00=Join-Path $p.RepositoryRoot 'Extracted/CERG/SingleCharacter/Recovery-BaseController/T1/locator-attempt.json';return $allowanceRejected-and$publicRejected-and-not[IO.File]::Exists($a00) }
Add-MbacrTest $ids[10] { $c=New-MbacrCase (Join-Path $base 'ce11');$other=Join-Path $base 'ce11-other';[IO.Directory]::CreateDirectory($other)|Out-Null;$rootRejected=Test-MbacrThrows {Invoke-MbacrControllerLocatorProducer -Attempt $c.Attempt -AttemptSha256 $c.AttemptSha256 -SelectorRows $c.Selectors -SourceRoot $other -OrderedArgumentTokens $c.ProducerArgs -Limits $c.Limits|Out-Null};$p=New-MbacrProductionCase (Join-Path $base 'ce11-repository');$foreign=Join-Path $base 'foreign-repository';[IO.Directory]::CreateDirectory($foreign)|Out-Null;$repositoryRejected=Test-MbacrThrows {Invoke-MbacrControllerLocatorForegroundCore -RepositoryRoot $foreign -SourceRoot $p.SourceRoot -SelectorRows $p.Selectors -ProducerOrderedArgumentTokens $p.ProducerArgs -ValidatorOrderedArgumentTokens $p.ValidatorArgs -Limits $p.Limits -InputArtifactRegistry $p.InputArtifactRegistry -ExactAuthorizationId $p.AuthorizationId -ExactTo02Sha256 $p.To02Sha256 -ExactRootFingerprint $p.RootFingerprint -ExactProducerImplementationId $p.ProducerImplementationId -ExactValidatorImplementationId $p.ValidatorImplementationId -ExactArgumentsFingerprint $p.ArgumentsFingerprint|Out-Null};return $rootRejected-and$repositoryRejected }
Add-MbacrTest $ids[11] { $c=New-MbacrCase (Join-Path $base 'ce12');$tampered=@($c.ProducerArgs)+@('--extra');return (Test-MbacrThrows {Invoke-MbacrControllerLocatorProducer -Attempt $c.Attempt -AttemptSha256 $c.AttemptSha256 -SelectorRows $c.Selectors -SourceRoot $c.Root -OrderedArgumentTokens $tampered -Limits $c.Limits|Out-Null}) }
Add-MbacrTest $ids[12] { $c=New-MbacrProductionCase (Join-Path $base 'ce13-final');$a00=Join-Path $c.RepositoryRoot 'Extracted/CERG/SingleCharacter/Recovery-BaseController/T1/locator-attempt.json';[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($a00))|Out-Null;[IO.File]::WriteAllText($a00,'immutable-attempt-sentinel');$before=Get-MbacrProducerFileHash $a00;$finalRejected=Test-MbacrThrows {Invoke-MbacrProductionCase $c|Out-Null};$c2=New-MbacrProductionCase (Join-Path $base 'ce13-temp');$tmp=Join-Path $c2.RepositoryRoot 'Extracted/CERG/SingleCharacter/Recovery-BaseController/T1/locator-attempt.json.tmp';[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($tmp))|Out-Null;[IO.File]::WriteAllText($tmp,'interrupted-attempt-sentinel');$tempRejected=Test-MbacrThrows {Invoke-MbacrProductionCase $c2|Out-Null};return $finalRejected-and$tempRejected-and(Get-MbacrProducerFileHash $a00)-ceq$before-and-not[IO.File]::Exists((Join-Path $c.RepositoryRoot 'Extracted/CERG/SingleCharacter/Recovery-BaseController/T1/controller-location.json'))-and-not[IO.File]::Exists((Join-Path $c2.RepositoryRoot 'Extracted/CERG/SingleCharacter/Recovery-BaseController/T1/controller-location.json')) }
Add-MbacrTest $ids[13] { $c=New-MbacrProductionCase (Join-Path $base 'sp01');$published=Invoke-MbacrProductionCase $c;$r=$published.artifact;return $r.schemaVersion-ceq'cerg-mbacr-controller-location/1.1.0'-and$r.artifactId-ceq'MBACR-L01'-and$r.contractHeadCommit-ceq('c'*40)-and(@($r.inputArtifactRefs|ForEach-Object artifactId)-join'|')-ceq'MBACR-I01|MBACR-I02|MBACR-TO02'-and$r.locatorAuthorization.to02Sha256-ceq$c.To02Sha256-and$r.locatorAttemptRef.artifactId-ceq'MBACR-A00'-and$r.locatorAttemptRef.sha256-ceq$published.attemptSha256-and$r.locatorAttemptRef.byteCount-eq$published.attemptByteCount-and$r.status-ceq'ControllerLocated'-and$r.openCounts.producer-eq2-and$r.openCounts.validator-eq2-and$r.openCounts.total-eq4-and(@($r.openRows|ForEach-Object implementationArtifactId)-join'|')-ceq'MBACR-TG01|MBACR-TG01|MBACR-TG02|MBACR-TG02'-and$r.locationRows.Count-eq1-and$r.locationRows[0].serializedTypeName-ceq'AnimatorController'-and$r.locationRows[0].serializedObjectId-ceq'1'-and$r.locationRows[0].proofKind-ceq'ParsedSerializedObject'-and-not[IO.File]::Exists($published.path+'.tmp') }

if((@($rows|ForEach-Object testId)-join'|')-cne($ids-join'|')){throw 'Test row order mismatch.'}
$failed=@($rows|Where-Object status -cne 'Passed')
if($failed.Count){$failed|ForEach-Object{"$($_.testId): $($_.evidenceLocator)"}|Write-Host;throw "MBACR fixture failures: $($failed.Count)/$($ids.Count)"}
if($PublishReadinessPath){if($ContractHeadCommit-notmatch'^[0-9a-f]{40}$'){throw 'ContractHeadCommit must be exact lowercase 40-hex.'};. $script:MbacrActualProducerPath;. $script:MbacrActualValidatorPath;$publishRoot=Join-Path $base 'publish-root';[IO.Directory]::CreateDirectory($publishRoot)|Out-Null;$rootBinding=Get-MbacrProducerRootBinding 'pc-install' $publishRoot;$pb=Get-MbacrProducerBinding $rootBinding @();$vb=Get-MbacrValidatorBinding $rootBinding @();$toolRows=@([pscustomobject][ordered]@{artifactId=$pb.artifactId;role=$pb.role;portableTrackedPath=$pb.portableTrackedPath;implementationVersion=$pb.implementationVersion;byteCount=$pb.byteCount;sha256=$pb.sha256},[pscustomobject][ordered]@{artifactId=$vb.artifactId;role=$vb.role;portableTrackedPath=$vb.portableTrackedPath;implementationVersion=$vb.implementationVersion;byteCount=$vb.byteCount;sha256=$vb.sha256});$artifact=[pscustomobject][ordered]@{schemaVersion='cerg-mbacr-tooling-readiness/1.1.0';artifactId='MBACR-TO02';contractHeadCommit=$ContractHeadCommit;toolRows=$toolRows;testRows=@($rows);status='Green';failures=@();nextAction='AwaitTotalControlAuditBeforeMBACRT1B'};$final=[IO.Path]::GetFullPath($PublishReadinessPath);$tmp=$final+'.tmp';if([IO.Path]::GetFileName($final)-cne'tooling-readiness-02.json'){throw 'TO02 final filename mismatch.'};[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($final))|Out-Null;if([IO.File]::Exists($final)-or[IO.File]::Exists($tmp)){throw 'Readiness final/temp already exists.'};$bytes=[Text.UTF8Encoding]::new($false).GetBytes((ConvertTo-MbacrProducerCanonicalJson $artifact));$s=[IO.File]::Open($tmp,'CreateNew','Write','None');try{$s.Write($bytes,0,$bytes.Length);$s.Flush($true)}finally{$s.Dispose()};[IO.File]::Move($tmp,$final,$false);$reopened=[Text.UTF8Encoding]::new($false).GetString([IO.File]::ReadAllBytes($final))|ConvertFrom-Json -Depth 100 -DateKind String;if((Get-MbacrProducerFileHash $final)-cne([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($bytes))).ToLowerInvariant()-or-not(Test-MbacrProducerExactObject $reopened $artifact)){throw 'Readiness reopen mismatch.'};Assert-MbacrProducerReadiness $reopened (Get-MbacrProducerFileHash $final) $pb $vb|Out-Null}
[pscustomobject][ordered]@{status='Green';passed=$rows.Count;failed=0;testRows=@($rows);readinessPath=$(if($PublishReadinessPath){[IO.Path]::GetFullPath($PublishReadinessPath)}else{$null})}
}finally{$junction=Join-Path $base 'ce04/root/linked';if([IO.Directory]::Exists($junction)){[IO.Directory]::Delete($junction)};if([IO.Directory]::Exists($base)){[IO.Directory]::Delete($base,$true)}}
