[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$script:MbacrValidatorUtf8=[Text.UTF8Encoding]::new($false)
$script:MbacrValidatorPath=$PSCommandPath

function ConvertTo-MbacrValidatorCanonicalJson {
    param([AllowNull()][object]$Value)
    if($null-eq$Value){return 'null'}
    if($Value-is[string]){return [Text.Json.JsonSerializer]::Serialize([object](([string]$Value).Normalize([Text.NormalizationForm]::FormC)),[string],[Text.Json.JsonSerializerOptions]::new())}
    if($Value-is[bool]){return $(if($Value){'true'}else{'false'})}
    if($Value-is[byte]-or$Value-is[int16]-or$Value-is[int32]-or$Value-is[int64]){return [Convert]::ToString($Value,[Globalization.CultureInfo]::InvariantCulture)}
    if($Value-is[Collections.IDictionary]){$a=[Collections.Generic.List[string]]::new();foreach($k in $Value.Keys){$a.Add((ConvertTo-MbacrValidatorCanonicalJson([string]$k))+':'+(ConvertTo-MbacrValidatorCanonicalJson $Value[$k]))};return '{'+($a-join',')+'}'}
    if($Value-is[pscustomobject]){$a=[Collections.Generic.List[string]]::new();foreach($p in $Value.PSObject.Properties){$a.Add((ConvertTo-MbacrValidatorCanonicalJson $p.Name)+':'+(ConvertTo-MbacrValidatorCanonicalJson $p.Value))};return '{'+($a-join',')+'}'}
    if($Value-is[Collections.IEnumerable]){$a=[Collections.Generic.List[string]]::new();foreach($x in $Value){$a.Add((ConvertTo-MbacrValidatorCanonicalJson $x))};return '['+($a-join',')+']'}
    throw "Unsupported validator JSON type $($Value.GetType().FullName)"
}
function Get-MbacrValidatorStructuredHash {param([string]$Domain,[object]$Payload);return ([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($script:MbacrValidatorUtf8.GetBytes((ConvertTo-MbacrValidatorCanonicalJson @($Domain,$Payload)))))).ToLowerInvariant()}
function Get-MbacrValidatorCanonicalHash {param([object]$Value);return ([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($script:MbacrValidatorUtf8.GetBytes((ConvertTo-MbacrValidatorCanonicalJson $Value))))).ToLowerInvariant()}
function Get-MbacrValidatorFileHash {param([string]$Path);$s=[IO.File]::Open($Path,'Open','Read','Read');try{$h=[Security.Cryptography.SHA256]::Create();try{return ([Convert]::ToHexString($h.ComputeHash($s))).ToLowerInvariant()}finally{$h.Dispose()}}finally{$s.Dispose()}}

function Test-MbacrValidatorPathChain {
    param([string]$Root,[string]$Leaf)
    $r=[IO.Path]::GetFullPath($Root).TrimEnd('\','/');$ri=[IO.DirectoryInfo]::new($r);$ri.Refresh();if(-not$ri.Exists-or($ri.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){return $false}
    $q=$ri.Parent;while($null-ne$q){$q.Refresh();if(-not$q.Exists-or($q.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){return $false};$q=$q.Parent}
    $f=[IO.Path]::GetFullPath($Leaf);if(-not$f.StartsWith($r+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){return $false};$q=[IO.DirectoryInfo]::new([IO.Path]::GetDirectoryName($f));while($q.FullName-cne$r){$q.Refresh();if(-not$q.Exists-or($q.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){return $false};$q=$q.Parent;if($null-eq$q){return $false}};return $true
}
function Get-MbacrValidatorRootBinding {param([string]$SourceId,[string]$Root);$r=[IO.Path]::GetFullPath($Root).TrimEnd('\','/');if(-not(Test-MbacrValidatorPathChain $r (Join-Path $r '__mbacr_probe__'))){throw 'Validator root chain invalid.'};return [pscustomobject][ordered]@{sourceId=$SourceId;privateAbsoluteReadOnlyRoot=$r;rootFingerprint=(Get-MbacrValidatorStructuredHash 'mbacr/source-root/1' @($SourceId,$r))}}
function Get-MbacrValidatorBinding {
    param([object]$SourceRootBinding,[string[]]$OrderedArgumentTokens)
    $f=[IO.FileInfo]::new($script:MbacrValidatorPath);$sha=Get-MbacrValidatorFileHash $f.FullName;$runtime=[Diagnostics.Process]::GetCurrentProcess().MainModule.FileName;$rf=[IO.FileInfo]::new($runtime);$rsha=Get-MbacrValidatorFileHash $runtime
    $aid='MBACR-TG02';$role='ControllerLocatorValidator';$portable='Tools/AssetImport/Test-MbacrControllerLocation.ps1';$version='MBACR-CONTROLLER-VALIDATOR/1';$product=[string]$rf.VersionInfo.ProductName;$fileVersion=[string]$rf.VersionInfo.FileVersion
    $iid='MBACRIMP-'+(Get-MbacrValidatorStructuredHash 'mbacr/locator-implementation/1' @($aid,$role,$portable,$version,[int64]$f.Length,$sha,$product,$fileVersion,[int64]$rf.Length,$rsha))
    return [pscustomobject][ordered]@{artifactId=$aid;implementationId=$iid;role=$role;portableTrackedPath=$portable;implementationVersion=$version;byteCount=[int64]$f.Length;sha256=$sha;runtimeProduct=$product;runtimeVersion=$fileVersion;runtimeByteCount=[int64]$rf.Length;runtimeSha256=$rsha;sourceRootBinding=$SourceRootBinding;orderedArgumentTokens=@($OrderedArgumentTokens)}
}
function Test-MbacrValidatorExact {param([object]$A,[object]$B);return (ConvertTo-MbacrValidatorCanonicalJson $A)-ceq(ConvertTo-MbacrValidatorCanonicalJson $B)}

if(-not('MbacrValidatorBinaryParser'-as[type])){
Add-Type -TypeDefinition @'
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;

public sealed class MbacrValidatorController {
 public string FileName; public int FileIndex; public int ObjectIndex; public long PathId; public string ObjectName="";
}
public static class MbacrValidatorBinaryParser {
 sealed class R { public byte[] X; public int I; public bool LE; public R(byte[] x,int i=0,bool le=false){X=x;I=i;LE=le;} void N(int n){if(n<0||I<0||I+n>X.Length)throw new InvalidDataException("Binary range failure.");} public byte B(){N(1);return X[I++];} public ushort W(){N(2);ushort v=LE?(ushort)(X[I]|X[I+1]<<8):(ushort)(X[I]<<8|X[I+1]);I+=2;return v;} public uint D(){N(4);uint v=LE?(uint)(X[I]|X[I+1]<<8|X[I+2]<<16|X[I+3]<<24):(uint)(X[I]<<24|X[I+1]<<16|X[I+2]<<8|X[I+3]);I+=4;return v;} public long Q(){N(8);ulong v=0;if(LE){for(int k=7;k>=0;k--)v=v*256+X[I+k];}else{for(int k=0;k<8;k++)v=v*256+X[I+k];}I+=8;return unchecked((long)v);} public string S(){int j=I;while(I<X.Length&&X[I]!=0)I++;if(I==X.Length)throw new InvalidDataException("String termination failure.");string s=Encoding.UTF8.GetString(X,j,I-j);I++;return s;} public void Skip(long n){if(n>int.MaxValue)throw new InvalidDataException("Skip too large.");N((int)n);I+=(int)n;} public void A4(){I=(I+3)&-4;N(0);} }
 sealed class Entry { public long O,L; public string N; }
 static byte[] ExpandLz4(byte[] input,int wanted){byte[] output=new byte[wanted];int ip=0,op=0;while(ip<input.Length){byte t=input[ip++];int literals=t>>4;if(literals==15){byte z;do{if(ip>=input.Length)throw new InvalidDataException("LZ4 literal length.");z=input[ip++];literals+=z;}while(z==255);}if(ip+literals>input.Length||op+literals>output.Length)throw new InvalidDataException("LZ4 literal copy.");Array.Copy(input,ip,output,op,literals);ip+=literals;op+=literals;if(ip==input.Length)break;if(ip+1>=input.Length)throw new InvalidDataException("LZ4 offset.");int back=input[ip]|input[ip+1]<<8;ip+=2;if(back==0||back>op)throw new InvalidDataException("LZ4 back reference.");int count=(t&15)+4;if((t&15)==15){byte z;do{if(ip>=input.Length)throw new InvalidDataException("LZ4 match length.");z=input[ip++];count+=z;}while(z==255);}if(op+count>output.Length)throw new InvalidDataException("LZ4 match copy.");while(count-->0){output[op]=output[op-back];op++;}}if(op!=wanted)throw new InvalidDataException("LZ4 output length.");return output;}
 static byte[] Unpack(byte[] x,int algorithm,int size){if(algorithm==0){if(x.Length!=size)throw new InvalidDataException("Stored length.");return x;}if(algorithm==2||algorithm==3)return ExpandLz4(x,size);throw new InvalidDataException("Compression algorithm.");}
 static List<Entry> Directory(byte[] bundle,out byte[] payload){R h=new R(bundle);if(h.S()!="UnityFS")throw new InvalidDataException("Signature.");if(h.D()<6)throw new InvalidDataException("Format.");h.S();h.S();long total=h.Q();uint packedInfo=h.D(),plainInfo=h.D(),flags=h.D();if(total!=bundle.LongLength)throw new InvalidDataException("Bundle length.");if((flags&0x200)!=0)h.I=(h.I+15)&-16;int infoAt=(flags&0x80)!=0?bundle.Length-(int)packedInfo:h.I;if(infoAt<0||infoAt+packedInfo>bundle.Length)throw new InvalidDataException("Info bounds.");byte[] p=new byte[packedInfo];Array.Copy(bundle,infoAt,p,0,(int)packedInfo);byte[] info=Unpack(p,(int)(flags&63),(int)plainInfo);int blocksAt=(flags&0x80)!=0?h.I:h.I+(int)packedInfo;R d=new R(info);d.Skip(16);uint blockCount=d.D();MemoryStream all=new MemoryStream();for(int i=0;i<blockCount;i++){int plain=checked((int)d.D()),packed=checked((int)d.D());int kind=d.W()&63;if(blocksAt+packed>bundle.Length)throw new InvalidDataException("Block bounds.");byte[] c=new byte[packed];Array.Copy(bundle,blocksAt,c,0,packed);blocksAt+=packed;byte[] q=Unpack(c,kind,plain);all.Write(q,0,q.Length);}uint entryCount=d.D();List<Entry> entries=new List<Entry>();for(int i=0;i<entryCount;i++){long o=d.Q(),l=d.Q();d.D();string n=d.S();if(o<0||l<0||o+l>all.Length)throw new InvalidDataException("Entry bounds.");entries.Add(new Entry{O=o,L=l,N=n});}payload=all.ToArray();return entries;}
 static void TypesAndObjects(byte[] asset,string node,int nodeIndex,List<MbacrValidatorController> answer){R head=new R(asset);uint metadata=head.D();head.D();uint ver=head.D();uint oldOffset=head.D();if(ver<9)throw new InvalidDataException("Serialized version.");bool little=head.B()==0;head.Skip(3);long dataOffset=oldOffset;if(ver>=22){metadata=head.D();head.Q();dataOffset=head.Q();head.Q();}if(metadata==0||dataOffset<head.I||dataOffset>asset.LongLength)throw new InvalidDataException("Serialized header.");R m=new R(asset,head.I,little);if(ver>=7)m.S();if(ver>=8)m.D();bool hasTree=ver>=13&&m.B()!=0;int typeCount=checked((int)m.D());if(typeCount<0||typeCount>100000)throw new InvalidDataException("Type count.");int[] classIds=new int[typeCount];for(int t=0;t<typeCount;t++){int cid=unchecked((int)m.D());classIds[t]=cid;if(ver>=16)m.B();if(ver>=17)m.W();if(ver>=13){if((ver<16&&cid<0)||cid==114)m.Skip(16);m.Skip(16);}if(hasTree){int nodes=checked((int)m.D()),text=checked((int)m.D());m.Skip(checked(nodes*(ver>=19?32:24)+text));}}if(ver>=7&&ver<14)m.D();int objectCount=checked((int)m.D());if(objectCount<0||objectCount>1000000)throw new InvalidDataException("Object count.");HashSet<long> ids=new HashSet<long>();for(int o=0;o<objectCount;o++){if(ver>=14)m.A4();long id=ver<14?unchecked((int)m.D()):m.Q();long start=ver>=22?m.Q():m.D();uint size=m.D();int type=unchecked((int)m.D());if(ver<16)m.W();if(ver<11)m.W();if(ver>=11&&ver<17)m.W();if(ver==15)m.B();if(!ids.Add(id))throw new InvalidDataException("Duplicate object ID.");if(type<0||type>=classIds.Length)throw new InvalidDataException("Type index.");if(start<0||dataOffset+start+size>asset.LongLength)throw new InvalidDataException("Object bounds.");if(classIds[type]==91)answer.Add(new MbacrValidatorController{FileName=node,FileIndex=nodeIndex,ObjectIndex=o,PathId=id});}}
 public static MbacrValidatorController[] Inspect(byte[] bundle){byte[] payload;List<Entry> entries=Directory(bundle,out payload);List<MbacrValidatorController> result=new List<MbacrValidatorController>();for(int i=0;i<entries.Count;i++){Entry e=entries[i];byte[] asset=new byte[e.L];Array.Copy(payload,(int)e.O,asset,0,(int)e.L);try{TypesAndObjects(asset,e.N,i,result);}catch(InvalidDataException){if(e.N.EndsWith(".resS",StringComparison.OrdinalIgnoreCase)||e.N.EndsWith(".resource",StringComparison.OrdinalIgnoreCase))continue;throw;}}return result.ToArray();}
}
'@
}

function Assert-MbacrValidatorFailureRows {
    param([object[]]$Rows)
    $seen=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal);$reasons=@('InputIdentityFailure','ParserFailure','LimitExceeded','ConservationFailure','ProducerValidatorDisagreement','OutputIntegrityFailure');$codes=@('LocatorAuthorizationMissingOrMismatch','AttemptReuseOrInterruption','WrongRoot','ArgumentTamper','OpenSequenceMismatch','MissingLeaf','NonRegularLeaf','LeafReparse','AncestorReparse','UnreadableLeaf','ByteCountMismatch','Sha256Mismatch','MalformedSerializedContainer','DuplicateControllerIdentity','ProducerValidatorMismatch','FilesReadExceeded','BytesReadExceeded','DurationExceeded','ResultRowsExceeded','ChildProcessObserved','SelectorCoverageMismatch','PartitionMismatch','ArtifactInstallFailure')
    foreach($r in @($Rows)){if((@($r.PSObject.Properties.Name)-join'|')-cne'failureId|selectorId|reasonCode|detailCode'-or$r.reasonCode-notin$reasons-or$r.detailCode-notin$codes){throw 'Noncanonical failure row.'};$id='MBACRF-'+(Get-MbacrValidatorStructuredHash 'mbacr/failure/2' @($r.selectorId,$r.reasonCode,$r.detailCode));if($r.failureId-cne$id-or-not$seen.Add($id)){throw 'Failure identity invalid or duplicate.'}}
    return $true
}
function New-MbacrValidatorFailure {param([AllowNull()][string]$SelectorId,[string]$Reason,[string]$Detail);return [pscustomobject][ordered]@{failureId='MBACRF-'+(Get-MbacrValidatorStructuredHash 'mbacr/failure/2' @($SelectorId,$Reason,$Detail));selectorId=$SelectorId;reasonCode=$Reason;detailCode=$Detail}}

function Assert-MbacrValidatorAttempt {
    param([object]$Attempt,[string]$AttemptSha256,[object]$Root,[object]$Binding,[object[]]$SelectorRows)
    if($Attempt.schemaVersion-cne'cerg-mbacr-locator-attempt/1.0.0'-or$Attempt.artifactId-cne'MBACR-A00'-or$Attempt.status-cne'ArmedNoSourceOpen'-or[int]$Attempt.allowanceUsedAfterInstall-ne1){throw 'Validator attempt state invalid.'}
    if(-not(Test-MbacrValidatorExact $Attempt.sourceRootBinding $Root)-or-not(Test-MbacrValidatorExact $Attempt.validatorBinding $Binding)){throw 'Validator root/binding mismatch.'}
    if($AttemptSha256-cne(Get-MbacrValidatorCanonicalHash $Attempt)){throw 'Validator attempt canonical SHA mismatch.'};$expectedPlan=@($SelectorRows|ForEach-Object{[pscustomobject][ordered]@{selectorId=$_.selectorId;sourceId=$_.sourceId;portableRelativePath=$_.portableRelativePath}});if(-not(Test-MbacrValidatorExact @($Attempt.selectorPlan) $expectedPlan)){throw 'Validator selector plan mismatch.'};$SelectorIds=@($expectedPlan|ForEach-Object selectorId)
    $a=$Attempt.locatorAuthorization;$args=Get-MbacrValidatorStructuredHash 'mbacr/locator-arguments/1' @($Attempt.producerBinding.orderedArgumentTokens,$Attempt.validatorBinding.orderedArgumentTokens)
    $expected='MBACRLOC-'+(Get-MbacrValidatorStructuredHash 'mbacr/locator-authorization/2' @($a.to01Sha256,$a.sourceId,$a.rootFingerprint,$a.producerImplementationId,$a.validatorImplementationId,$a.orderedArgumentTokensFingerprint,@($a.selectorIds),[int]$a.maxProducerSourceOpens,[int]$a.maxValidatorSourceOpens,[int]$a.maxTotalSourceOpens,[bool]$a.noLO))
    if($a.authorizationId-cne$expected-or$a.to01Sha256-cne$Attempt.to01Sha256-or$a.sourceId-cne$Root.sourceId-or$a.rootFingerprint-cne$Root.rootFingerprint-or$a.producerImplementationId-cne$Attempt.producerBinding.implementationId-or$a.validatorImplementationId-cne$Binding.implementationId-or$a.orderedArgumentTokensFingerprint-cne$args-or(@($a.selectorIds)-join'|')-cne($SelectorIds-join'|')-or[int]$a.maxTotalSourceOpens-ne4-or-not[bool]$a.noLO){throw 'Validator authorization mismatch.'}
}

function Invoke-MbacrControllerLocatorValidator {
    [CmdletBinding()]
    param([Parameter(Mandatory=$true)][object]$Attempt,[Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-f]{64}$')][string]$AttemptSha256,[Parameter(Mandatory=$true)][object]$ProducerPacket,[Parameter(Mandatory=$true)][object[]]$SelectorRows,[Parameter(Mandatory=$true)][string]$SourceRoot,[Parameter(Mandatory=$true)][string[]]$OrderedArgumentTokens,[Parameter(Mandatory=$true)][object]$Limits)
    if(@($SelectorRows).Count-ne2-or$ProducerPacket.schemaVersion-cne'cerg-mbacr-producer-packet/1.0.0'-or$ProducerPacket.producerBinding.sha256-ceq(Get-MbacrValidatorFileHash $script:MbacrValidatorPath)){throw 'Validator input or independence invalid.'}
    if($ProducerPacket.attemptSha256-cne$AttemptSha256){throw 'Producer packet attempt SHA mismatch.'};$root=Get-MbacrValidatorRootBinding 'pc-install' $SourceRoot;$binding=Get-MbacrValidatorBinding $root $OrderedArgumentTokens;Assert-MbacrValidatorAttempt $Attempt $AttemptSha256 $root $binding $SelectorRows
    $started=[DateTimeOffset]::UtcNow;$total=[int64]0;$validatorResults=[Collections.Generic.List[object]]::new();$validatorOpens=[Collections.Generic.List[object]]::new();$failures=[Collections.Generic.List[object]]::new()
    for($i=0;$i-lt2;$i++){$s=$SelectorRows[$i];$leaf=[IO.Path]::GetFullPath((Join-Path $root.privateAbsoluteReadOnlyRoot ([string]$s.portableRelativePath).Replace('/',[IO.Path]::DirectorySeparatorChar)));$status='InvalidCurrentLeaf';$count=$null;$hash=$null;$controllers=@();$detail=$null
        if(-not(Test-MbacrValidatorPathChain $root.privateAbsoluteReadOnlyRoot $leaf)){$detail='AncestorReparse'}elseif(-not[IO.File]::Exists($leaf)){$detail='MissingLeaf'}else{$fi=[IO.FileInfo]::new($leaf);if(($fi.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){$detail='LeafReparse'}else{$stream=[IO.File]::Open($leaf,'Open','Read','Read');try{$bytes=[byte[]]::new([int]$stream.Length);$offset=0;while($offset-lt$bytes.Length){$n=$stream.Read($bytes,$offset,$bytes.Length-$offset);if($n-le0){throw 'EOF'};$offset+=$n}}finally{$stream.Dispose()};$count=[int64]$bytes.Length;$total+=$count;if($total-gt[int64]$Limits.maxBytesRead){$detail='BytesReadExceeded'}else{$hash=([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($bytes))).ToLowerInvariant();try{$controllers=@([MbacrValidatorBinaryParser]::Inspect($bytes));$status=$(if($controllers.Count){'Located'}else{'NotLocated'})}catch{$detail='MalformedSerializedContainer'}};$validatorOpens.Add([pscustomobject][ordered]@{implementationArtifactId='MBACR-TG02';implementationId=$binding.implementationId;selectorId=$s.selectorId;sourceId=$s.sourceId;portableRelativePath=$s.portableRelativePath;openedAtUtc=[DateTimeOffset]::UtcNow.ToString('O');byteCount=$count;sha256=$hash})}}
        $validatorResults.Add([pscustomobject][ordered]@{selectorId=$s.selectorId;sourceId=$s.sourceId;portableRelativePath=$s.portableRelativePath;currentByteCount=$count;currentSha256=$hash;status=$status;detailCode=$detail;controllers=@($controllers)})
    }
    if(([DateTimeOffset]::UtcNow-$started).TotalSeconds-gt[int]$Limits.maxDurationSeconds){$failures.Add((New-MbacrValidatorFailure $null 'LimitExceeded' 'DurationExceeded'))}
    $producerBy=@{};foreach($r in @($ProducerPacket.selectorResults)){$producerBy[[string]$r.selectorId]=$r}
    $selectorOut=[Collections.Generic.List[object]]::new();$locations=[Collections.Generic.List[object]]::new()
    foreach($vr in @($validatorResults)){$pr=$producerBy[[string]$vr.selectorId];if($null-eq$pr-or$pr.status-cne$vr.status-or$pr.currentByteCount-ne$vr.currentByteCount-or$pr.currentSha256-cne$vr.currentSha256-or(@($pr.controllers).Count-ne@($vr.controllers).Count)){$failures.Add((New-MbacrValidatorFailure $vr.selectorId 'ProducerValidatorDisagreement' 'ProducerValidatorMismatch'))}
        else{for($j=0;$j-lt@($vr.controllers).Count;$j++){$pc=@($pr.controllers)[$j];$vc=@($vr.controllers)[$j];if($pc.SerializedFileName-cne$vc.FileName-or[int]$pc.SerializedFileOrdinal-ne[int]$vc.FileIndex-or[int]$pc.ObjectOrdinal-ne[int]$vc.ObjectIndex-or[int64]$pc.ObjectId-ne[int64]$vc.PathId){$failures.Add((New-MbacrValidatorFailure $vr.selectorId 'ProducerValidatorDisagreement' 'ProducerValidatorMismatch'));break}}}
        $base=@($SelectorRows|Where-Object selectorId -CEQ $vr.selectorId)[0];$selectorOut.Add([pscustomobject][ordered]@{selectorId=$base.selectorId;sourceId=$base.sourceId;portableRelativePath=$base.portableRelativePath;ledgerByteCount=[int64]$base.ledgerByteCount;ledgerSha256=$base.ledgerSha256;currentByteCount=$vr.currentByteCount;currentSha256=$vr.currentSha256;status=$vr.status})
        if($vr.status-ceq'InvalidCurrentLeaf'){$code=$(if($null-ne$vr.detailCode){$vr.detailCode}else{'UnreadableLeaf'});$failures.Add((New-MbacrValidatorFailure $vr.selectorId 'ParserFailure' $code))}
        for($j=0;$j-lt@($vr.controllers).Count;$j++){$c=@($vr.controllers)[$j];$proof=[pscustomobject][ordered]@{serializedFileName=$c.FileName;serializedFileOrdinal=[int]$c.FileIndex;objectOrdinal=[int]$c.ObjectIndex};$oid=[Convert]::ToString([int64]$c.PathId,[Globalization.CultureInfo]::InvariantCulture);$lid='CTRLLOC-'+(Get-MbacrValidatorStructuredHash 'mbacr/controller-location/2' @($vr.selectorId,[int64]$vr.currentByteCount,$vr.currentSha256,'AnimatorController',$oid,[string]$c.ObjectName,'ParsedSerializedObject',$proof,'Located'));$locations.Add([pscustomobject][ordered]@{locationId=$lid;selectorId=$vr.selectorId;currentByteCount=[int64]$vr.currentByteCount;currentSha256=$vr.currentSha256;serializedTypeName='AnimatorController';serializedObjectId=$oid;objectName=[string]$c.ObjectName;proofKind='ParsedSerializedObject';proofLocator=$proof;status='Located'})}
    }
    $located=@($selectorOut|Where-Object status -CEQ 'Located').Count;$not=@($selectorOut|Where-Object status -CEQ 'NotLocated').Count;$invalid=@($selectorOut|Where-Object status -CEQ 'InvalidCurrentLeaf').Count;if($located-eq0){$failures.Add((New-MbacrValidatorFailure $null 'ConservationFailure' 'PartitionMismatch'))}
    $attemptSha=$AttemptSha256;$openRows=[Collections.Generic.List[object]]::new();$ordinal=0
    foreach($o in (@($ProducerPacket.producerOpenRows)+@($validatorOpens))){$ordinal++;$id='MBACROPEN-'+(Get-MbacrValidatorStructuredHash 'mbacr/locator-open/1' @($attemptSha,$ordinal,$o.implementationId,$o.selectorId,$o.sourceId,$o.portableRelativePath,[int64]$o.byteCount,$o.sha256));$openRows.Add([pscustomobject][ordered]@{openId=$id;openOrdinal=$ordinal;implementationArtifactId=$o.implementationArtifactId;implementationId=$o.implementationId;selectorId=$o.selectorId;sourceId=$o.sourceId;portableRelativePath=$o.portableRelativePath;openedAtUtc=$o.openedAtUtc;byteCount=$o.byteCount;sha256=$o.sha256})}
    if($openRows.Count-ne4){$failures.Add((New-MbacrValidatorFailure $null 'ConservationFailure' 'OpenSequenceMismatch'))}
    $failureArray=@($failures|Sort-Object failureId -CaseSensitive);Assert-MbacrValidatorFailureRows $failureArray|Out-Null
    return [pscustomobject][ordered]@{schemaVersion='cerg-mbacr-controller-location/1.0.0';artifactId='MBACR-L01-SYNTHETIC';locatorAttemptRef=[pscustomobject][ordered]@{artifactId='MBACR-A00';portableRelativePath='Synthetic/locator-attempt.json';byteCount=[int64](ConvertTo-MbacrValidatorCanonicalJson $Attempt).Length;sha256=$attemptSha};locatorAuthorization=$Attempt.locatorAuthorization;sourceRootBinding=$root;selectorRows=@($selectorOut);locationRows=@($locations|Sort-Object locationId -CaseSensitive);openRows=@($openRows);openCounts=[pscustomobject][ordered]@{producer=2;validator=2;total=$openRows.Count};partitions=[pscustomobject][ordered]@{selectorCount=2;locatedCount=$located;notLocatedCount=$not;invalidCurrentLeafCount=$invalid;controllerLocationCount=$locations.Count};limits=$Limits;producerBinding=$Attempt.producerBinding;validatorBinding=$binding;status=$(if($failureArray.Count-eq0){'ControllerLocated'}else{'Failed'});failures=$failureArray;nextAction=$(if($failureArray.Count-eq0){'AwaitTotalControlAuditBeforeMBACRT2'}else{'RecoveryRouteFailed'})}
}
