[CmdletBinding()]param()
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'Invoke-CergLo1R2AtomicHandoff.ps1')
. (Join-Path $PSScriptRoot 'New-CergLo1ResultGraph.ps1')
$ids=@('R2A-CE01-ConfirmationMismatch','R2A-CE02-SourceDrift','R2A-CE03-ExpiredBeforeOpen','R2A-CE04-ForeignProcess','R2A-CE05-A01WithoutFirstOpen','R2A-SP01-AtomicHandoff')
$results=[Collections.Generic.List[object]]::new();function Add-AResult($id,[scriptblock]$body){try{&$body;$results.Add([pscustomobject][ordered]@{testId=$id;status='Passed';evidenceLocator="SyntheticFixture/$id/Assertions"})}catch{throw "$id failed: $($_.Exception.Message)"}}
function Test-AThrows([scriptblock]$body){$ok=$false;try{&$body|Out-Null}catch{$ok=$true};if(-not$ok){throw'Expected failed-closed exception.'}}
$baseIds=@('R2-CE01-Missing','R2-CE02-Directory','R2-CE03-Reparse','R2-CE04-ByteDrift','R2-CE05-EqualSizeHashDrift','R2-CE06-SelectorConservation','R2-CE07-IndependentDisagreement','R2-CE08-StaleRun','R2-CE09-HiddenField','R2-CE10-ProducerSplice','R2-CE11-AncestorReparse','R2-SP01-ProductionConstructor','R2-SP02-IndependentValidator','R2-SP03-StagingConsumer','R2-AT01-SelectorMutation','R2-AT02-TupleMutation','R2-AT03-EvidenceMutation','R2-AT04-TimeMutation','R2-AT05-ImplementationMutation')
function Write-AJson($path,$value){[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($path))|Out-Null;[IO.File]::WriteAllText($path,(ConvertTo-CergCanonicalJsonValue $value),[Text.UTF8Encoding]::new($false))}
function New-AFixture($caseRoot){
    $sourceRoot=Join-Path $caseRoot 'Source';[IO.Directory]::CreateDirectory($sourceRoot)|Out-Null;$members=[Collections.Generic.List[object]]::new()
    for($i=0;$i-lt17;$i++){$rel=('leaf/{0:D2}.bin'-f$i);$leaf=Join-Path $sourceRoot $rel.Replace('/','\');[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($leaf))|Out-Null;[IO.File]::WriteAllBytes($leaf,[Text.Encoding]::UTF8.GetBytes("a-plus-$i"));$members.Add([pscustomobject][ordered]@{memberId="OLD-$i";sourceId='synthetic';portableRelativePath=$rel;sizeBytes=[int64]([IO.FileInfo]::new($leaf).Length);sha256=(Get-FileHash -Algorithm SHA256 $leaf).Hash.ToLowerInvariant()})}
    $head='1234567890abcdef1234567890abcdef12345678';$candidate=[pscustomobject][ordered]@{schemaVersion='cerg-t1-candidate-lock/2.2.0';artifactId='CERG-T1V22-O01';contractHeadCommit=$head;status='Passed';selectedCandidateId='char_14401';attackAnchors=@();sourceMembers=@($members);discoveryObligations=@()};$candidatePath=Join-Path $caseRoot 'candidate.json';Write-AJson $candidatePath $candidate;$candidateSha=Get-CergSha256Hex $candidatePath
    $bindings=@([pscustomobject][ordered]@{sourceId='synthetic';privateAbsoluteReadOnlyRoot=$sourceRoot});$packet=Invoke-CergLo1R2FreshnessProducer $candidate $candidatePath $bindings $head $candidateSha ([DateTimeOffset]::UtcNow.ToString('O'));$validator=Get-CergR2ValidatorImplementation;$refs=@($packet.producerImplementation.implementationId,$validator.implementationId);$rows=@($baseIds|ForEach-Object{[pscustomobject][ordered]@{testId=$_;status='Passed';evidenceRefIds=$refs}});$f01=Invoke-CergLo1R2FreshnessValidator $packet $bindings $rows[0..10] $rows[11..13] $rows[14..18];$f01Path=Join-Path $caseRoot 'freshness.json';[IO.File]::WriteAllText($f01Path,(ConvertTo-CergR2ValidatorJson $f01),[Text.UTF8Encoding]::new($false));$f01Sha=Get-CergSha256Hex $f01Path
    $attemptRoot=Join-Path $caseRoot 'Attempt';$planRows=@($f01.currentMembers|ForEach-Object{[pscustomobject][ordered]@{sourceMemberRefId=$_.memberId;sourceId=$_.sourceId;sourcePortableRelativePath=$_.portableRelativePath;stagingPortableRelativePath=('Extracted/CERG/SingleCharacter/LO-CERG1-R2/Input/'+$_.sourceId+'/'+$_.portableRelativePath);byteCount=[int64]$_.byteCount;sha256=$_.sha256}}|Sort-Object stagingPortableRelativePath -CaseSensitive);$bytes=[int64](($planRows|Measure-Object byteCount -Sum).Sum);$memberIds=@($planRows|ForEach-Object sourceMemberRefId)
    $definition=[pscustomobject][ordered]@{schemaVersion='cerg-lo-cerg1-preflight-definition/1.1.0';artifactId='LO-CERG1-P01-DEFINITION';candidateLockSha256=$candidateSha;freshnessEvidenceSha256=$f01Sha;freshnessCheckRunId=$f01.checkRunId;freshnessValidatorFinishedAtUtc=$f01.validatorFinishedAtUtc;contractHeadCommit=$head;selectedCandidateId='char_14401';createdAt=[DateTimeOffset]::UtcNow.ToString('O');sourceRootBindings=@([pscustomobject][ordered]@{sourceId='synthetic';privateAbsoluteReadOnlyRoot=$sourceRoot;rootFingerprint=('f'*64)});implementationBindings=@();operation=[pscustomobject][ordered]@{operationId='R2-OP';obligationRefIds=@('R2-OB');implementationRefIds=@();inputMemberRefIds=$memberIds;expectedSubjectKinds=@();expectedRelationshipKinds=@();sourceReadMaxFiles=17;sourceReadMaxBytes=$bytes;maxDurationSeconds=60;maxResultRows=1;maxOutputFiles=100;maxOutputBytes=$bytes;stagingInputPortablePath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/Input';outputPortablePath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/Output';workPortablePath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/Work'};aggregateLimits=[pscustomobject][ordered]@{sourceReadMaxFiles=17;sourceReadMaxBytes=$bytes;maxDurationSeconds=60;maxResultRows=1;maxOutputFiles=100;maxOutputBytes=$bytes};stagingPlan=[pscustomobject][ordered]@{stagingInputPortablePath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/Input';stagingInventoryTemporaryPath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/staging-inventory.json.tmp';stagingInventoryPath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/staging-inventory.json';workPortablePath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/Work';outputPortablePath='Extracted/CERG/SingleCharacter/LO-CERG1-R2/Output';memberRows=$planRows;memberCount=17;byteCount=$bytes;memberSetFingerprint=(Get-CergStructuredSha256 'cerg-lo1/staging-member-set/1' @($planRows))};status='Green';nextAction='RequestExactHumanConfirmationForLOCERG1'}
    $p01=New-CergLo1R2PreflightObject $definition $f01 $f01Path $attemptRoot;$p01Path=Join-Path $caseRoot 'preflight.json';Write-AJson $p01Path $p01;$runner=Get-CergR2AtomicRunnerImplementation;$v14=@(1..23|ForEach-Object{'T1A3-TEST{0:D2}'-f$_})+@('T1A4-TEST24','T1A4-TEST25');$allTests=@($baseIds+$ids+$v14|ForEach-Object{[pscustomobject][ordered]@{testId=$_;status='Passed';evidenceLocator="SyntheticFixture/$_/Assertions"}});$repoRoot=[IO.Directory]::GetParent([IO.Directory]::GetParent($PSScriptRoot).FullName).FullName;$toolPaths=@('Tools/AssetImport/Invoke-CergLo1ExactStaging.ps1','Tools/AssetImport/Invoke-CergLo1R2AtomicHandoff.ps1','Tools/AssetImport/New-CergLo1Preflight.ps1','Tools/AssetImport/New-CergLo1R2Freshness.ps1','Tools/AssetImport/New-CergLo1ResultGraph.ps1','Tools/AssetImport/Test-CergLo1Pipeline.ps1','Tools/AssetImport/Test-CergLo1R2AtomicHandoff.ps1','Tools/AssetImport/Test-CergLo1R2Freshness.ps1','Tools/AssetImport/Test-CergLo1R2FreshnessPipeline.ps1');$n=0;$toolRows=@($toolPaths|ForEach-Object{$leaf=[IO.Path]::Combine($repoRoot,$_.Replace('/',[IO.Path]::DirectorySeparatorChar));$item=Get-Item -LiteralPath $leaf;$n++;[pscustomobject][ordered]@{artifactId=('R2-A-T{0:D2}'-f$n);role='BoundImplementation';portableRelativePath=$_;byteCount=[int64]$item.Length;sha256=Get-CergSha256Hex $leaf}});$readiness=[pscustomobject][ordered]@{schemaVersion='cerg-r2-aplus-readiness/1.0.0';artifactId='R2-TO03';contractHeadCommit=$head;toolRows=$toolRows;testRows=$allTests;status='Green';failures=@();nextAction='AwaitTotalControlAuditBeforeR2P01'};$readinessPath=Join-Path $caseRoot 'readiness.json';Write-AJson $readinessPath $readiness;$confirmation=Get-CergR2ConfirmationId $head $f01Sha $f01.checkRunId $f01.currentMemberSetFingerprint (Get-CergSha256Hex $p01Path) $runner.implementationId
    [pscustomobject]@{Candidate=$candidate;CandidatePath=$candidatePath;F01Path=$f01Path;P01Path=$p01Path;ReadinessPath=$readinessPath;ConfirmationId=$confirmation;SourceRoot=$sourceRoot;AttemptRoot=$attemptRoot;F02Temp=(Join-Path $attemptRoot 'freshness-adjacency.json.tmp');F02=(Join-Path $attemptRoot 'freshness-adjacency.json');A01Temp=(Join-Path $attemptRoot 'attempt-state.json.tmp');A01=(Join-Path $attemptRoot 'attempt-state.json');H01Temp=(Join-Path $attemptRoot 'first-source-open.json.tmp');H01=(Join-Path $attemptRoot 'first-source-open.json');SITemp=(Join-Path $attemptRoot 'staging-inventory.json.tmp');SI=(Join-Path $attemptRoot 'staging-inventory.json')}
}
function Invoke-AFixture($f,[string]$confirmation=$f.ConfirmationId){Invoke-CergLo1R2AtomicHandoff $f.CandidatePath $f.F01Path $f.P01Path $f.ReadinessPath $confirmation $f.F02Temp $f.F02 $f.A01Temp $f.A01 $f.H01Temp $f.H01 $f.SITemp $f.SI}
$base=[IO.Path]::Combine([IO.Path]::GetTempPath(),'cerg-r2a-'+[guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($base)|Out-Null
try{
    Add-AResult $ids[0] {$f=New-AFixture (Join-Path $base 'confirm');Test-AThrows{Invoke-AFixture $f ('R2CONF-'+('0'*64))};if([IO.File]::Exists($f.F02)-or[IO.File]::Exists($f.A01)){throw'Confirmation mismatch created outputs.'}}
    Add-AResult $ids[1] {$f=New-AFixture (Join-Path $base 'drift');$leaf=Join-Path $f.SourceRoot 'leaf\00.bin';[IO.File]::WriteAllBytes($leaf,[Text.Encoding]::UTF8.GetBytes('drifted'));Test-AThrows{Invoke-AFixture $f};if([IO.File]::Exists($f.A01)){throw'Source drift created A01.'}}
    Add-AResult $ids[2] {$f=New-AFixture (Join-Path $base 'expired');[IO.Directory]::CreateDirectory($f.AttemptRoot)|Out-Null;[IO.File]::WriteAllText($f.A01,'{}');$token=New-CergR2AtomicHandoffToken 'i' 'r' ([DateTimeOffset]::UtcNow.AddSeconds(-11).ToString('O')) $f.A01 (Get-CergSha256Hex $f.A01) $f.H01Temp $f.H01;Test-AThrows{Complete-CergR2AtomicFirstSourceOpen $token 'R2M-expired'};$h=Read-CergJsonFile $f.H01;if($h.status-cne'FirstSourceOpenAfterDeadline'-or$h.LOUsedAfterFirstSourceOpen-ne2-or$h.nextAction-cne'FailClosedNoReuse'-or-not$token.firstSourceOpenObserved){throw'Late first open was not recorded as consumed failure.'}}
    Add-AResult $ids[3] {$f=New-AFixture (Join-Path $base 'foreign');[IO.Directory]::CreateDirectory($f.AttemptRoot)|Out-Null;[IO.File]::WriteAllText($f.A01,'{}');$token=New-CergR2AtomicHandoffToken 'i' 'r' ([DateTimeOffset]::UtcNow.ToString('O')) $f.A01 (Get-CergSha256Hex $f.A01) $f.H01Temp $f.H01;$token.processId=[int64]$PID+1;Test-AThrows{Assert-CergR2AtomicHandoffToken $token};$script:CergActiveR2HandoffSecret=$null}
    Add-AResult $ids[4] {$f=New-AFixture (Join-Path $base 'no-open');[IO.Directory]::CreateDirectory($f.AttemptRoot)|Out-Null;[IO.File]::WriteAllText($f.A01,'{}');$token=New-CergR2AtomicHandoffToken 'i' 'r' ([DateTimeOffset]::UtcNow.ToString('O')) $f.A01 (Get-CergSha256Hex $f.A01) $f.H01Temp $f.H01;if([IO.File]::Exists($f.H01)-or$token.firstSourceOpenObserved){throw'A01 alone consumed LO.'};$script:CergActiveR2HandoffSecret=$null}
    Add-AResult $ids[5] {$f=New-AFixture (Join-Path $base 'valid');$r=Invoke-AFixture $f;$h=Read-CergJsonFile $f.H01;if(-not[IO.File]::Exists($f.F02)-or-not[IO.File]::Exists($f.A01)-or-not[IO.File]::Exists($f.H01)-or-not[IO.File]::Exists($f.SI)-or$h.elapsedMilliseconds-gt10000-or$h.LOUsedBeforeFirstSourceOpen-ne1-or$h.LOUsedAfterFirstSourceOpen-ne2-or$r.stagingInventory.memberCount-ne17){throw'Atomic handoff success vector invalid.'};$a=Read-CergJsonFile $f.A01;$p=Read-CergJsonFile $f.P01Path;$f01=Read-CergJsonFile $f.F01Path;$si=Read-CergJsonFile $f.SI;$null=Assert-CergUpstreamBindings -Candidate $f.Candidate -Preflight $p -Freshness $f01 -FreshnessEvidencePath $f.F01Path -Attempt $a -Staging $si -CandidatePath $f.CandidatePath -PreflightPath $f.P01Path -AttemptStatePath $f.A01 -FirstSourceOpenReceiptPath $f.H01 -StagingInventoryPath $f.SI -OutputRoot $p.stagingPlan.outputPrivateAbsolutePath}
    if($results.Count-ne6){throw'A+ test conservation failed.'};[pscustomobject][ordered]@{total=6;passed=6;failed=0;testRows=@($results)}|ConvertTo-Json -Depth 8
}finally{if([IO.Directory]::Exists($base)){Remove-Item -LiteralPath $base -Recurse -Force}}
